<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm password_cpassword</name>
   <tag></tag>
   <elementGuidId>7a930e8a-01e7-48ab-9f05-cc41bbe960f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cpassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cpassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdcb1244-f1df-44fa-9d53-c252dc1f4b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2309a3b9-afe0-4a58-b4ca-9d649e238707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cpassword</value>
      <webElementGuid>60975b36-7fd9-4f51-9c07-43c9fc42528b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>33ae59b3-2d3d-43dd-adbf-c18e74e430f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cpassword&quot;)</value>
      <webElementGuid>9e1d4681-1ef8-4b8c-b139-6e0f23c0f549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/07 - User Profile Icon (Top Right)/TC_69-update_New_Password/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>a9d2f7b2-6847-4af1-8d5b-7163ef0bc60f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cpassword']</value>
      <webElementGuid>916991b9-6886-455b-bb4f-82babcfd3623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div[5]/div[3]/div/input</value>
      <webElementGuid>d4ae4152-1547-49c4-a908-2882387b45ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>9a9b5aac-e8f9-41b4-8d5c-0c118d55ed4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'cpassword']</value>
      <webElementGuid>4721c8f2-4439-493e-86bd-1b18badede29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
