<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>01d75fa3-6cd4-4baa-88ca-fd09ce346d10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#7b425a0a-4101-4101-886c-94a1badec98f</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'OK' or . = 'OK') and @ref_element = 'Object Repository/TC_33-start_Attendance/Page_Home page/iframe_Self services_homePageFrame (3)']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to mark the close of the day?'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c27db8a4-a8eb-4fda-b785-cabd1df1b947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>aa3a181b-799e-4dda-9853-e7d179d0a358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7b425a0a-4101-4101-886c-94a1badec98f</value>
      <webElementGuid>bc2986b9-d284-438e-9724-7a8d4f70b17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>4018601b-ecc3-4b67-99c9-08fa3fc974dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7b425a0a-4101-4101-886c-94a1badec98f&quot;)</value>
      <webElementGuid>fcc4ef9e-7970-4eee-824f-c22de110cba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_33-start_Attendance/Page_Home page/iframe_Self services_homePageFrame (3)</value>
      <webElementGuid>9f9a5f6e-9c2c-4aa7-b182-02715bbfd786</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='7b425a0a-4101-4101-886c-94a1badec98f']</value>
      <webElementGuid>d3e99355-9774-48a1-b0c5-a150e9bb6045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a3f1ce54-24ee-4656-ba6c-e8cc0122f0ba']/div/div/div[3]/div/div/button</value>
      <webElementGuid>2dee23be-c429-45b7-a388-dc659b9ba2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to mark the close of the day?'])[1]/following::button[1]</value>
      <webElementGuid>55b5722d-003c-4288-8d00-c2a8751d10d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation message'])[1]/following::button[1]</value>
      <webElementGuid>9389bd33-169f-4599-bc56-b46d91ef3458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>73674473-544e-4b5f-9db2-d03c5b1b2332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>6810f163-9db4-4fb7-9390-8bf3904eca28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>2f426e27-3234-443e-8efd-4ade199360ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '7b425a0a-4101-4101-886c-94a1badec98f' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>46416f9d-674c-4f0b-a19f-ad5a0ca81309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
