<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_End day</name>
   <tag></tag>
   <elementGuidId>5a330908-02e4-485c-bcc4-c339f8453a0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.attendance-widget-endbtn-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='attendance_content']/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e37f9d0a-15c1-4651-949a-5e1bae80d462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attendance-widget-endbtn-txt</value>
      <webElementGuid>bd988bf3-95e7-461c-ac47-fa94f801dfd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> End day  </value>
      <webElementGuid>7ee994e6-9ac1-46c3-b5d5-8f27fad21408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendance_content&quot;)/a[@class=&quot;attendance-widget-endbtn&quot;]/span[@class=&quot;attendance-widget-endbtn-txt&quot;]</value>
      <webElementGuid>cb675ad6-7b17-430b-8fd5-f3586504d598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_33-start_Attendance/Page_Home page/iframe_Self services_homePageFrame (2)</value>
      <webElementGuid>93c83b3d-5a1a-42af-9607-886eddf8af66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attendance_content']/a[2]/span</value>
      <webElementGuid>0fc14673-da37-414a-8794-3bd0bb6d14ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total hours'])[1]/following::span[2]</value>
      <webElementGuid>36ad8a79-1d29-4827-bc7c-106942ac80b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::span[1]</value>
      <webElementGuid>39689bca-fdc4-4dea-aec9-40bfd1de687a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::span[1]</value>
      <webElementGuid>7de65d99-c85c-4b16-9ef5-342e5554b83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>ba2bb63f-9dc5-4946-8013-47122b3b7411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' End day  ' or . = ' End day  ')]</value>
      <webElementGuid>fc705c02-81cd-495e-90ed-bdae072e9ca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
