<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_emp  10</name>
   <tag></tag>
   <elementGuidId>eff81b63-ea4e-4546-8cef-7bf4d27cb59b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1004825</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1004825']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5379ccf3-0c8c-489f-aba1-65dce5d8a72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1004825</value>
      <webElementGuid>6749c30b-1e31-4a24-abe3-864cbca7dd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>95fc3f1a-13a4-48b4-b67f-955e89e35f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>emp  10 </value>
      <webElementGuid>7640154e-3f1d-4f28-9615-86f7f6968a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1004825&quot;)</value>
      <webElementGuid>8cb95a6f-5053-41fd-854d-90d311a8992f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1004825']</value>
      <webElementGuid>c00d08fc-a8b0-467e-b35b-85e8e2ba5a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[10]</value>
      <webElementGuid>5617d0c4-47bd-4160-a225-5d17a96f4b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]</value>
      <webElementGuid>abb2e218-8609-4780-8551-b70327f48821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1004825' and (text() = 'emp  10 ' or . = 'emp  10 ')]</value>
      <webElementGuid>24dc7c8e-748f-4139-8124-340c9be3446d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
