<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Message_chatMessageContent</name>
   <tag></tag>
   <elementGuidId>b3f22d4b-79aa-41f7-99c2-c7901e6a30dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chatMessageContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='chatMessageContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>44914b43-311e-488f-8ae5-2409ca325d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chatMessageContent</value>
      <webElementGuid>9d0bfcf8-96a4-4f42-93ec-3d38d13850f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>4f1643be-c219-47ba-bd06-f1514affca6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1b3b2b28-599a-45e8-997e-c4c1519f1a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bc15f6ab-435b-4c4d-841c-ed56df1e063c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chatMessageContent&quot;)</value>
      <webElementGuid>fd02ade1-e62a-4dea-b0a8-7ffa672afc23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='chatMessageContent']</value>
      <webElementGuid>42d12118-46aa-493d-b81e-3977ba7d0028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div[4]/textarea</value>
      <webElementGuid>3aa34ec2-f7d8-4d53-891a-a7b35128218c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cac827be-819a-4497-88e5-d36d40f74c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'chatMessageContent']</value>
      <webElementGuid>49db6a1d-17a2-4839-8754-7d981b9cdb10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
