<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Emp 05_Like_comment</name>
   <tag></tag>
   <elementGuidId>04b3fa4b-4e5f-4e51-9ef0-ddda4b140dc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='like_img_1000012']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;like_img_1000012&quot;)[count(. | //*[@id = 'like_img_1000012' and @src = 'https://images.empxtrack.com/images/client-images/8/photo2_2.gif' and @title = 'emp 05' and @ref_element = 'Object Repository/04-TC_020_put_Like_On_Users/Page_Home page/iframe__mycontent-right-frame']) = count(//*[@id = 'like_img_1000012' and @src = 'https://images.empxtrack.com/images/client-images/8/photo2_2.gif' and @title = 'emp 05' and @ref_element = 'Object Repository/04-TC_020_put_Like_On_Users/Page_Home page/iframe__mycontent-right-frame'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#like_img_1000012</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ee6d3dcd-996f-4ed3-9be1-911bc274c764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>like_img_1000012</value>
      <webElementGuid>7b46429b-1bcf-4305-8906-4b6fa5e84dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>1874ea75-27a6-4ff2-a43b-3713e8f4c0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>e1c6ddf8-098c-4b4c-9d94-4afe88f7bf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.empxtrack.com/images/client-images/8/photo2_2.gif</value>
      <webElementGuid>395fc2e2-be80-4dc7-89ed-7d0a897b1aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>emp 05</value>
      <webElementGuid>c8b9f216-9ace-4efa-a020-503de4149a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;like_img_1000012&quot;)</value>
      <webElementGuid>7ec0eade-d79b-455c-be9c-139a35c3c949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Dashboard/05 - Feed/05-TC_020_put_Like_On_Users/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>da3725b7-3a32-4f4f-938e-65eb7ddf2fa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='like_img_1000012']</value>
      <webElementGuid>6054f17a-4307-4be4-b4b1-668399f3e6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='like_box_1000012']/img[3]</value>
      <webElementGuid>d1bd99c6-9e7d-4e5b-b2d9-cca51d2985ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='emp 05']</value>
      <webElementGuid>126d6b61-b0a2-41ad-8fe3-42d129659e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[3]</value>
      <webElementGuid>fba84553-e792-4983-975c-aeb39eb19aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'like_img_1000012' and @src = 'https://images.empxtrack.com/images/client-images/8/photo2_2.gif' and @title = 'emp 05']</value>
      <webElementGuid>d6617323-3a94-472c-9f5f-c0948673c7a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
