<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>2ce685e6-66a3-4ae1-9545-fe3907541b75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#8051c464-e2f8-49d0-b132-34842dcdec5c</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'OK' or . = 'OK') and @ref_element = 'Object Repository/05 -Self-services/TC_43-add_Hobbies_Empty_Information/Page_Home page/iframe__mycontent-right-frame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid text.'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1fff2c03-4c14-43f8-8604-8a0fd0736a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>38668d72-8af3-466e-93d1-8fa6aa62d617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8051c464-e2f8-49d0-b132-34842dcdec5c</value>
      <webElementGuid>71a00132-f1c4-4a24-8aca-2d3ccc12ca5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>9f2d1b2c-c11d-43c1-bed5-ec2d99f61018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8051c464-e2f8-49d0-b132-34842dcdec5c&quot;)</value>
      <webElementGuid>1a2d5b09-5dfc-447d-8108-3e60bfb46a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_43-add_Hobbies_Empty_Information/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>9593672a-f754-4ba1-a5dd-56498d5367c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='8051c464-e2f8-49d0-b132-34842dcdec5c']</value>
      <webElementGuid>8da35a40-861f-44c5-b993-0c01277b636b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b0a8c34f-98ce-4049-9197-cccdb33c81db']/div/div/div[3]/div/div/button</value>
      <webElementGuid>88716f29-7951-416b-8104-bd84a366f971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter valid text.'])[1]/following::button[1]</value>
      <webElementGuid>820832c8-a67b-4faa-8b3a-a7ce02425843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>f45ce0b2-24f4-4ac6-aa22-2f9d5e2d9ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>1ebaa984-c0d4-4e90-a1d3-e4fc8b1c8502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>a11a0539-f923-403f-a76a-06c7ad01ced2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '8051c464-e2f8-49d0-b132-34842dcdec5c' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>11a28fbf-f990-46e9-8ace-571bd8658bde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
