<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your Session has expired. Please log _6da4ef</name>
   <tag></tag>
   <elementGuidId>d8e115ee-9715-4441-ad0f-b291362d45a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5004795b-62ee-4a48-bfba-23bf85e5769e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8a74ae35-fb0e-4070-be8f-5319ad85e706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>9cadb832-2a97-40b4-83ce-61ca8339f7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7cdafcc8-8872-4865-9240-a480ebf29aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pId</value>
      <webElementGuid>4311ea95-72f6-41a9-aee7-3aedbd555dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box lock</value>
      <webElementGuid>0cf40856-b84d-441b-9b97-28240b06a6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:detect_Key(event);</value>
      <webElementGuid>8302bb13-a18b-46ca-986d-6803b85f2235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>document.logonForm.password.select();</value>
      <webElementGuid>729b00fa-4f7d-4787-8dd5-4f9c420c9b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pId&quot;)</value>
      <webElementGuid>7d64d01a-6d75-4020-ac04-ef4c976bb90a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pId']</value>
      <webElementGuid>fc8c9ba4-d09e-4de3-a3c0-8e8d56b7d333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>6cc04845-79ec-49cc-bae5-6a0b909f360e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @name = 'password' and @id = 'pId']</value>
      <webElementGuid>fa85a5c8-ca8b-4227-8aca-08f4e3d3327c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
