<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Time based activities</name>
   <tag></tag>
   <elementGuidId>b94a6aa3-0450-47e7-9506-a6518eafe003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#allTimeItems > h3 > strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='allTimeItems']/h3/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>099c98b4-64f9-4177-8cd8-3712e176eabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time based activities</value>
      <webElementGuid>57f223cc-0fb6-4d78-9d09-50688144d704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allTimeItems&quot;)/h3[1]/strong[1]</value>
      <webElementGuid>44995e5c-70e0-4fdf-a4d6-942e95cf25fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allTimeItems']/h3/strong</value>
      <webElementGuid>a83f97cb-ebb7-490d-8753-dade5cf8301d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[2]/following::strong[1]</value>
      <webElementGuid>970fdccd-6beb-4acb-b34a-2cf871d315b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance'])[1]/preceding::strong[1]</value>
      <webElementGuid>1a9df0de-1e52-474e-a4db-10ae64d2e52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Time based activities']/parent::*</value>
      <webElementGuid>954b1869-c919-4621-8c14-a23935fea43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/h3/strong</value>
      <webElementGuid>7c181559-91b9-4e24-890d-7900e5c22903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Time based activities' or . = 'Time based activities')]</value>
      <webElementGuid>1950a678-afeb-4a71-b80a-46a6614997d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
