<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>1baaa233-177e-4131-9a7f-6ccce5b5f6cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'cf3dcdd1-dda5-433f-a9ac-5ec97046c557' and (text() = 'OK' or . = 'OK') and @ref_element = 'Object Repository/04-TC_016-unsuccessfully_Save_Blank_Task/Page_Home page/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cf3dcdd1-dda5-433f-a9ac-5ec97046c557</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>40fc4275-0ba1-443f-8e3b-c857c81b352d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>a5b8aabd-366d-4ddb-9592-a50fc68c0110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cf3dcdd1-dda5-433f-a9ac-5ec97046c557</value>
      <webElementGuid>29cf9caf-e5e4-4f33-aea4-cc6df3b51c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>2356516e-c475-42e9-91bf-0359990180eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cf3dcdd1-dda5-433f-a9ac-5ec97046c557&quot;)</value>
      <webElementGuid>8c4f1c67-bf23-4bd0-8734-b8262f6c653e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Dashboard/04.1 - Event/TC_016-unsuccessfully_Save_Blank_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>e914747a-d130-4787-916c-820f651ad72c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cf3dcdd1-dda5-433f-a9ac-5ec97046c557']</value>
      <webElementGuid>6eb1a8ea-bcd2-42c0-a412-463df25f10c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='2edfbb0c-46e4-49ea-99bc-ee88b1e96fa9']/div/div/div[3]/div/div/button</value>
      <webElementGuid>269f2a44-2746-48f0-8a7a-80fa30dfac69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please specify the subject'])[1]/following::button[1]</value>
      <webElementGuid>47a25cf9-73dd-4293-86bd-3a7efa89225b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>0cca2c60-b8e3-47f0-aa2c-7f89e509aeb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>730bdf68-6b88-4dae-93c7-e6dbcc97764a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>5a01d2d1-7205-40bf-b642-60a849e44761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cf3dcdd1-dda5-433f-a9ac-5ec97046c557' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>aab17003-a67b-4529-bf58-6b92abfd3f64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
