<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Self services_homePageFrame</name>
   <tag></tag>
   <elementGuidId>f391a2f8-7f03-47b0-8e52-3a7cb4cf8fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='homePageFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#homePageFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2c250626-b0d9-47d3-a0eb-2d137b87ff61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=c7rx7N8xkXknprpz06dlP2J%2FdJEzP4ngFbARIA2bIHenwFJJ7suSW+ATSBCWtA0VeFp8us9jRHmZeyi78fc7sw%3D%3D</value>
      <webElementGuid>8f96984f-0097-453d-9485-5c07d04c25c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>776124d4-7c1b-4175-bab9-adab5c56b2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay_homePageFrame</value>
      <webElementGuid>8e413786-cadb-498f-a13d-d8f319e10bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>homePageFrame</value>
      <webElementGuid>34ed40ce-3d5d-41b0-ba03-279351ce76e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homePageFrame&quot;)</value>
      <webElementGuid>77c034f9-4efb-4e1b-ab0d-4f30a6cf57f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='homePageFrame']</value>
      <webElementGuid>59a7c93a-a85c-4325-bd18-b8d79d167295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section']/iframe</value>
      <webElementGuid>e2fa4232-b39c-4df0-9f92-21b5d9304fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9f6e6818-edf6-492d-af10-f5a7bdb9a448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'runet.do?activity=submit&amp;enc=c7rx7N8xkXknprpz06dlP2J%2FdJEzP4ngFbARIA2bIHenwFJJ7suSW+ATSBCWtA0VeFp8us9jRHmZeyi78fc7sw%3D%3D' and @id = 'homePageFrame' and @name = 'homePageFrame']</value>
      <webElementGuid>1f44eab0-a080-443e-8710-5b7fe7f261ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
