<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hobbies</name>
   <tag></tag>
   <elementGuidId>930f7ff1-51e6-4161-a9c6-036677002e28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hobbies</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hobbies']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f9fa149-5aed-4685-b010-1fed64ab9b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3cee4324-6427-4091-9f6a-d14774d19503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f37bade1-8d31-4ed8-882e-f440580d5d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobbies</value>
      <webElementGuid>fb624e59-ea11-449e-81a3-71b8bd305b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject[0].empHobbies.hobbies</value>
      <webElementGuid>89d6908f-49a4-4a40-b8db-285dbfd71ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>numericFilter(this);return false;</value>
      <webElementGuid>7cca0754-a060-42b7-ba06-cbfe48200f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hobbies&quot;)</value>
      <webElementGuid>a10fac4a-cb78-49cc-8b3a-e3590f63a9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_42-add_Hobbies/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>3281a4a2-e9f6-4490-9be7-ccf2a17ebf49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hobbies']</value>
      <webElementGuid>e75ca1a2-00ce-48b7-88a5-674bbb6943da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[7]/div[2]/input</value>
      <webElementGuid>23e1b644-e529-4f5b-b528-a934e8ae1aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/input</value>
      <webElementGuid>ec7c6069-2ffc-431d-9d05-d3588ee2cf85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'hobbies' and @name = 'dataObject[0].empHobbies.hobbies']</value>
      <webElementGuid>6e3a99b3-9fb2-426b-9cf6-30182a1291fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
