<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_Add_Comment_button</name>
   <tag></tag>
   <elementGuidId>3556ec71-7c25-424e-a7fe-7183e409ec83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;buddy_box_1000011&quot;)/div[@class=&quot;col-md-12 comment-box&quot;]/div[@class=&quot;col-md-2&quot;]/a[@id=&quot;jsFunUpdate_-1&quot;]/i[@class=&quot;fa fa-paper-plane&quot;][count(. | //i[@class = 'fa fa-paper-plane' and @ref_element = 'Object Repository/04 - Dashboard/05 - Feed/05-TC_017-success_Add_Comment/Page_Home page/iframe__mycontent-right-frame']) = count(//i[@class = 'fa fa-paper-plane' and @ref_element = 'Object Repository/04 - Dashboard/05 - Feed/05-TC_017-success_Add_Comment/Page_Home page/iframe__mycontent-right-frame'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[6]/div[2]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buddy_box_1000011 > div.col-md-12.comment-box > div.col-md-2 > #jsFunUpdate_-1 > i.fa.fa-paper-plane</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3264c9ab-7eca-4b3c-a504-e3d2b4496748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-paper-plane</value>
      <webElementGuid>66a64138-fe9a-416c-9cae-dad1605c80d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buddy_box_1000011&quot;)/div[@class=&quot;col-md-12 comment-box&quot;]/div[@class=&quot;col-md-2&quot;]/a[@id=&quot;jsFunUpdate_-1&quot;]/i[@class=&quot;fa fa-paper-plane&quot;]</value>
      <webElementGuid>bcfd226b-9f5d-4a11-acd5-e707b28a0191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Dashboard/05 - Feed/05-TC_017-success_Add_Comment/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>054f2446-5479-43d8-9146-eb0644df61cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='jsFunUpdate_-1']/i)[2]</value>
      <webElementGuid>61fc4a06-04a6-48c6-a990-4ecb6e50c7a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/div[2]/a/i</value>
      <webElementGuid>1bcb9dcb-c113-458e-9d3c-20165fbf1569</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
