<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Say hello to emp 09</name>
   <tag></tag>
   <elementGuidId>f37479f0-5f49-4f15-a675-a091587eda48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;_reponse_note_1000011&quot;)[count(. | //input[@type = 'text' and @id = '_reponse_note_1000011' and @placeholder = 'Enter your comment' and @ref_element = 'Object Repository/04 - Dashboard/05 - Feed/05-TC_017-success_Add_Comment/Page_Home page/iframe__mycontent-right-frame']) = count(//input[@type = 'text' and @id = '_reponse_note_1000011' and @placeholder = 'Enter your comment' and @ref_element = 'Object Repository/04 - Dashboard/05 - Feed/05-TC_017-success_Add_Comment/Page_Home page/iframe__mycontent-right-frame'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buddy_box_1000011']/div[6]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_reponse_note_1000011</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d61b7e46-5893-4988-98fa-0272e7857128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a2e4222-d5a9-445c-a445-4d1f7d13752f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_reponse_note_1000011</value>
      <webElementGuid>d76b7a4d-ffc3-41f3-b385-6c747d0a6f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3657f8e8-f04d-47aa-85f1-caed08b19d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your comment</value>
      <webElementGuid>c1fd6a15-ab38-4c56-9e7b-7b35b67f0a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_reponse_note_1000011&quot;)</value>
      <webElementGuid>3a559fe5-8148-49b1-9146-ee09c0cbb843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Dashboard/05 - Feed/05-TC_017-success_Add_Comment/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>c24ec557-6af9-4d87-a75e-9ad005943de4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_reponse_note_1000011']</value>
      <webElementGuid>8a5d6e40-540c-4355-adff-069982e6c92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buddy_box_1000011']/div[6]/div/div[2]/input</value>
      <webElementGuid>1c4f01ec-5da3-47cd-a380-f7aadb8441a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[6]/div/div[2]/input</value>
      <webElementGuid>feb9ee32-5c2d-43c0-aee3-06b3f919ff3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '_reponse_note_1000011' and @placeholder = 'Enter your comment']</value>
      <webElementGuid>8baf188a-0f53-4b5d-b308-18b4ea2628b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
