<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_My profile</name>
   <tag></tag>
   <elementGuidId>5478f59a-f8f6-4275-ba37-40cb7a6e16e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#displayEmpPersonalDetail_headerV10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='displayEmpPersonalDetail_headerV10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>104beea0-c5c8-48c2-b0c8-61547cb37661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayEmpPersonalDetail_headerV10</value>
      <webElementGuid>faa5740d-0eba-4be9-a600-fbdda0cd8ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v10widget-tite-font</value>
      <webElementGuid>7d33647e-6ccb-4a70-ade3-e93ad64b6708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> My profile</value>
      <webElementGuid>af31ed23-cfd1-4101-8932-d3f954a710c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayEmpPersonalDetail_headerV10&quot;)</value>
      <webElementGuid>53879c97-26d0-48b2-82c8-5343ce93245b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_40-self-service_view_profile/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>bf4f8af1-9324-4b71-9904-309ee6407dcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='displayEmpPersonalDetail_headerV10']</value>
      <webElementGuid>19b3fb59-2b28-4b2b-9584-5440fda7031a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='head-areaV10']/h2</value>
      <webElementGuid>ecf5b302-5b26-4d0e-be8d-32ca70a4fc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My profile']/parent::*</value>
      <webElementGuid>c1f03ef0-34a8-4eb9-a579-79b8b4d29499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>1badd6ad-3c94-46d0-8ca7-0b8b6ff8777b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'displayEmpPersonalDetail_headerV10' and (text() = ' My profile' or . = ' My profile')]</value>
      <webElementGuid>4fcb234f-4ee4-40f3-91ba-1f656bcaf5d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
