<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>f42507ea-5590-4334-80ec-a237a862ad70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notificationItems123 > a.pull-right > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='notificationItems123']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c5c27294-10ef-4e4f-a738-366fe4848683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/v10/notification.png</value>
      <webElementGuid>1ee46d32-10a9-4df2-b0b5-04799f8bd327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notificationItems123&quot;)/a[@class=&quot;pull-right&quot;]/img[1]</value>
      <webElementGuid>a0e5dd05-eaa7-413c-855e-724cc1af5276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='notificationItems123']/a/img</value>
      <webElementGuid>2e56fe91-90bf-4712-8e10-8b4d3dd3e32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
      <webElementGuid>8a7261a9-965d-4af4-98c3-3f05cd33e686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/v10/notification.png']</value>
      <webElementGuid>ab989db2-bfc1-4549-a32f-be2b6fffba57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
