<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apply</name>
   <tag></tag>
   <elementGuidId>2572fc88-9238-4956-be90-0b3b99199d8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Apply')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@title = 'Apply' and (text() = ' Apply' or . = ' Apply') and @ref_element = 'Object Repository/06-TC_026_success_Apply_Casual Leave/Page_Home page (1)/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#actionItems_renderTableHeaderArray_1706427226824_0_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>53a0678c-fbe3-46f1-91cf-aabb9b6cfeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>5d8c8c31-3fa2-472c-b54f-83df9a5025eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>triggerMenuClose('_navBarId_renderTableHeaderArray_1706427226824_0');javascript:addLeaveRecord('1');return false;</value>
      <webElementGuid>cd1f3901-a92c-433b-927e-625d3766b993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actionItems_renderTableHeaderArray_1706427226824_0_0</value>
      <webElementGuid>509e7476-3b1b-4cd2-b0ed-c0d1c338c271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>3b6c20b6-62f5-4948-ac7a-58beeb9a4ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Apply</value>
      <webElementGuid>fd5aa832-ada5-4bfb-808a-b22fb15cf146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actionItems_renderTableHeaderArray_1706427226824_0_0&quot;)</value>
      <webElementGuid>7c268f3f-ecd0-4764-bc7a-176727f946b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04.3 - Leave/TC_026_success_Apply_Casual Leave (1)/Page_Home page (1)/iframe_Self services_homePageFrame</value>
      <webElementGuid>d4b28414-3e22-440c-a7e6-0f8b0f061bc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='actionItems_renderTableHeaderArray_1706427226824_0_0']</value>
      <webElementGuid>ca2c935c-726c-4c67-b66d-f92297357ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='renderTableHeaderArray']/tbody/tr/td[3]/div/ul/li/a</value>
      <webElementGuid>32cd5361-e308-432c-adee-11d07916a8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Apply')]</value>
      <webElementGuid>7824e57b-b866-4d2a-a71a-44cd9494c657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[1]/following::a[1]</value>
      <webElementGuid>cd0ef35c-074f-440f-aa1b-792542b13b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casual Leave'])[1]/following::a[2]</value>
      <webElementGuid>526e9908-c217-45c4-9066-2893e9f75dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Earned Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>7549dc8d-1594-4a7e-804f-5a0fff395ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[2]/preceding::a[1]</value>
      <webElementGuid>246393d0-dd1d-4ff7-ab49-99dbdf4de564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
      <webElementGuid>3dc4ed15-0c94-4c3c-bcde-a1a190f7e844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[4]</value>
      <webElementGuid>8c895bf9-7c2a-4c90-bc17-fb08cbe40e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>6e170ce6-906e-42cf-b9de-f0fee8df6219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'actionItems_renderTableHeaderArray_1706427226824_0_0' and @title = 'Apply' and (text() = ' Apply' or . = ' Apply')]</value>
      <webElementGuid>3d4cfe69-3095-47af-8b96-4009390a0531</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
