<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>c2c3dd27-10a4-48b3-8fc0-05149e83f679</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='84a35b82-68e0-4486-bf6f-35489014584b']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#84a35b82-68e0-4486-bf6f-35489014584b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c62f9e6-2a3e-4468-81fe-5d5efb50959f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>0dc0fa55-e545-4b99-9951-9c63d3c8225b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>84a35b82-68e0-4486-bf6f-35489014584b</value>
      <webElementGuid>0c845a6e-0d6e-4c0a-83e6-231a6edcb438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>991464c3-80c0-40c0-87f0-2eaf49484c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;84a35b82-68e0-4486-bf6f-35489014584b&quot;)</value>
      <webElementGuid>ceeabf54-3c0e-4b43-9662-34a40a18cb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04.3 - Leave/TC_026_success_Apply_Casual Leave/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>d2e2a9f3-5cf8-4dfe-a5c8-6400b5a3548e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/06 - Leave/06-TC_026_success_Apply_Casual Leave (1)/Page_Home page (1)/iframe_Self services_homePageFrame</value>
      <webElementGuid>59ac4826-ea97-47e5-8f7b-1db32b49939c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='84a35b82-68e0-4486-bf6f-35489014584b']</value>
      <webElementGuid>6e4e985e-ab97-4939-a94f-2c5b7263090a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f8168dc5-fdec-4d0e-9009-9899527be338']/div/div/div[3]/div/div/button</value>
      <webElementGuid>ed62e6e2-eba9-4df8-b4d6-4a317ee264e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>74eace1f-31bb-4b76-9377-393d1c6bd6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/following::button[1]</value>
      <webElementGuid>dd2b4344-a9be-4c85-8378-c7c5f01fde0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>1ff9adad-e0c8-4d05-901e-181b7b06b8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>c297bbc4-b6c9-4f92-a53d-4d4156a74757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '84a35b82-68e0-4486-bf6f-35489014584b' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>17ec8b99-3680-483f-b9c6-b8fe7e831db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
