<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>4e6aa475-6736-47ab-8317-872e1962e809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#05b77d3d-4ef3-49bb-b352-6b2e2faf2018</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'OK' or . = 'OK') and @ref_element = 'Object Repository/06-TC_031-applied_Sick_Leave/Page_Home page/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3bb5528a-334d-4666-a0d6-9c4dd1847319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>2dfaeae1-13b0-4495-8c1d-4e3f52580130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>05b77d3d-4ef3-49bb-b352-6b2e2faf2018</value>
      <webElementGuid>9092dbce-7138-43e4-9876-a3c51ffe0a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>d2be4489-b7d9-47e4-bd3b-c4b907f99108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;05b77d3d-4ef3-49bb-b352-6b2e2faf2018&quot;)</value>
      <webElementGuid>f8138e5d-805d-4006-9334-7a4eb23ffd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/06 - Leave/06-TC_031-applied_Sick_Leave/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>f80222fe-06e3-477d-9b48-96c1e7aace63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='05b77d3d-4ef3-49bb-b352-6b2e2faf2018']</value>
      <webElementGuid>d0745968-717b-489d-9317-8d622234eedb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cc9719a5-9b99-4bd2-8afa-1547df022b90']/div/div/div[3]/div/div/button</value>
      <webElementGuid>50999d67-3560-4252-a78c-735367088f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>d1b2de78-c68b-4c2e-af82-d166f5f13186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/following::button[1]</value>
      <webElementGuid>a1fa423f-ca8e-48c5-b7aa-61c83f5a63f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>055e522d-0d6d-4a76-a4f2-c4df6c8edf33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>93be68f5-f980-4daa-98d9-59b73e29ad20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '05b77d3d-4ef3-49bb-b352-6b2e2faf2018' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>02a341b7-d30e-4318-8543-fcac6f318220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
