<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Duration_Start Date</name>
   <tag></tag>
   <elementGuidId>52e09f77-4efc-4e4a-b55b-a0f4086850a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d64fe507-9295-4aa2-b897-2d5b48332448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>62cde042-8b83-491f-b034-16ac1b0dc364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>400b58d2-7d09-4e08-81c0-b748a7453c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_dataObject.startDate</value>
      <webElementGuid>19ee8fe1-68e7-4e73-8b93-aa9aba942257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f4393ea8-fb82-4280-80bd-d3229c96deef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>9d267dd9-bfaf-4be4-8fae-2fe87fa1995f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:calculateDays('Yes', '');return false;</value>
      <webElementGuid>439ca353-52f4-46fd-b079-2eedfbb7db23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start date</value>
      <webElementGuid>98ab7947-a0a9-48a0-b98e-eca548a00457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startDate&quot;)</value>
      <webElementGuid>f25abcb8-bd62-4fce-b477-2a81be643e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/06 - Leave/06-TC_031-applied_Sick_Leave/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>84c61bc9-c060-4d31-b112-0e091d217a65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startDate']</value>
      <webElementGuid>b39d77e9-1ade-4082-9f40-596ed3787fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='durationCtr']/div/input</value>
      <webElementGuid>eb9525ba-8a65-4cc0-9f08-691b7ae7a307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/input</value>
      <webElementGuid>9abf2c08-ca43-47a2-be4b-347860c155ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'date_dataObject.startDate' and @id = 'startDate' and @placeholder = 'Start date']</value>
      <webElementGuid>f67af264-72b1-4c09-84b7-cca478aec0d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
