<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Attendance</name>
   <tag></tag>
   <elementGuidId>b41f3fbc-f030-40b8-8d9f-097694d85ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#heading_page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='heading_page']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f57d272a-3e55-4af6-9686-333bec947da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>heading_page</value>
      <webElementGuid>a557ec7b-5e51-42a0-b7d7-f8da089db59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading_page</value>
      <webElementGuid>05ee101e-6983-4334-a79a-1ee650afbb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attendance</value>
      <webElementGuid>cab63889-d6f9-48b5-9e3c-612a79f7e453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heading_page&quot;)</value>
      <webElementGuid>d6f59ede-9501-4538-b813-511202a13ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_37-see_All_Attendance/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>1f923f3d-84a2-4c79-a7f4-1a88b9ebd73b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='heading_page']</value>
      <webElementGuid>837821ab-d436-438d-b82b-10c98e0b9f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div/h2</value>
      <webElementGuid>003d693b-e261-4855-b7cd-ebb203f89b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::h2[1]</value>
      <webElementGuid>f9333fdd-7544-474d-a6db-0e70be0b1c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attendance']/parent::*</value>
      <webElementGuid>466ebd9b-54d2-4f56-be10-39b42e69df87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>b8c8fb6a-c8e2-48e4-ba5d-f236d8175aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'heading_page' and (text() = 'Attendance' or . = 'Attendance')]</value>
      <webElementGuid>0d32785e-868f-4f33-b59a-14f7108982bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
