<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_User Name is not recognized</name>
   <tag></tag>
   <elementGuidId>5ec019d8-eade-4af1-a1f4-36c69a846e66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='m16_errorMsgOnPopUpEmploginProblem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#m16_errorMsgOnPopUpEmploginProblem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aee816bf-1935-458d-a8ec-af957b4c8fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>err</value>
      <webElementGuid>db6539d2-d53b-4a97-bf86-71ec02e867de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m16_errorMsgOnPopUpEmploginProblem</value>
      <webElementGuid>2a4b1c1f-ae03-42a1-adde-b245e48a36f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Name is not recognized.</value>
      <webElementGuid>facf133a-f79b-4864-b884-85c146f1ab68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m16_errorMsgOnPopUpEmploginProblem&quot;)</value>
      <webElementGuid>1dfcbb8e-a035-4934-a5dd-0ed5097bac37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='m16_errorMsgOnPopUpEmploginProblem']</value>
      <webElementGuid>9e9fc31d-2f5e-48e3-aeb3-16b412cf530a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='errorMsgOnPopUpEmploginProblem']/div</value>
      <webElementGuid>91873038-46b9-4e7d-b4f7-3b66194b9354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login problems'])[1]/following::div[2]</value>
      <webElementGuid>a857136d-b2e2-4ad6-b5db-d7e5a2c864e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © Saigun Technologies Pvt. Ltd. India. All rights reserved. Confidential'])[1]/following::div[9]</value>
      <webElementGuid>e77658b6-6a6f-400c-9db2-227a461b3587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Name is not recognized.']/parent::*</value>
      <webElementGuid>45583f6b-e487-41cf-aa96-bb9ba0046cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>5c0ae50d-895f-4bf0-8913-09be132ab4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'm16_errorMsgOnPopUpEmploginProblem' and (text() = 'User Name is not recognized.' or . = 'User Name is not recognized.')]</value>
      <webElementGuid>010577c2-1e9a-4679-88d5-2ac0f0bef57d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
