<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The workflow has been created</name>
   <tag></tag>
   <elementGuidId>bd492ef1-4747-4b67-abc5-89fd27f270e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.msgContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='snackbar']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b070ab06-042f-41e7-99e9-659cfc551e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>msgContent</value>
      <webElementGuid>9c2312e0-67ac-4013-a3f5-005c1b74829d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The workflow has been created.</value>
      <webElementGuid>33dfc4e2-5edd-4346-8713-6ec6cbc2ffbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snackbar&quot;)/div[@class=&quot;msgContent&quot;]</value>
      <webElementGuid>0a66ab72-1b9a-4373-b420-17f12d979851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_48-regularize_Attendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>ab69f9de-9cbc-4dcd-af5a-9bb259050755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='snackbar']/div</value>
      <webElementGuid>588ee64b-d135-406a-8977-702a278e308b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[0]'])[1]/following::div[15]</value>
      <webElementGuid>6acf6556-90ca-4983-9a79-2b3215d5a782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::div[1]</value>
      <webElementGuid>1044d5d9-d606-42a7-af8c-11e1857039bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'snackbar', '&quot;', ')/div[@class=', '&quot;', 'msgContent', '&quot;', ']')])[1]/preceding::div[9]</value>
      <webElementGuid>a02fc7bb-6d61-403e-a809-cc89d387bb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The workflow has been created.']/parent::*</value>
      <webElementGuid>3c93afbb-6a48-451e-9aaf-8cf795eb908c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div</value>
      <webElementGuid>7861b33e-cd55-4fc1-ba4a-6f5cdb3c9625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'The workflow has been created.' or . = 'The workflow has been created.')]</value>
      <webElementGuid>71dc2966-4e7b-4bb2-8200-672f006b38b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
