<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Attendance</name>
   <tag></tag>
   <elementGuidId>e5421763-5d42-4405-ae4b-0c3b8533c105</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myAttendance_headerV10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='myAttendance_headerV10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>75068cd2-22b5-40ef-8c1b-cdfe616849fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myAttendance_headerV10</value>
      <webElementGuid>102bf919-f2ce-41a5-8105-b6a2c93fb615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v10widget-tite-font</value>
      <webElementGuid>927f077b-4077-4fc4-8817-f35ad2fecf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Attendance</value>
      <webElementGuid>3701a14f-4d5b-4e40-83a3-0bb960cdf972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAttendance_headerV10&quot;)</value>
      <webElementGuid>ffd85390-b3bd-450d-8f34-99420acc1ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_48-regularize_Attendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>0e14699d-3255-469f-9717-3da94d0e4fe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='myAttendance_headerV10']</value>
      <webElementGuid>9e9616b5-1047-45a6-a870-86b443a9802f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='head-areaV10']/h2)[3]</value>
      <webElementGuid>4181a395-2f0d-4aa1-bdc8-8494c5a3bdb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Leave Policy'])[1]/following::h2[1]</value>
      <webElementGuid>55534148-7e91-434f-a99d-44c987783813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday Calendar'])[1]/following::h2[1]</value>
      <webElementGuid>7e16797f-a14f-44a8-82bf-14d9bdd8e316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todays In-Time'])[1]/preceding::h2[1]</value>
      <webElementGuid>ea799663-faf5-49f5-94cf-821d463bc873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attendance']/parent::*</value>
      <webElementGuid>e9abb171-8b68-45bc-88d3-1c5fdc53531c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/h2</value>
      <webElementGuid>ba40899a-6e52-4c6a-8432-62c4769178a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'myAttendance_headerV10' and (text() = ' Attendance' or . = ' Attendance')]</value>
      <webElementGuid>4c3bb781-5116-4736-8e97-e8722edc1351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
