<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Modify_employeeShift</name>
   <tag></tag>
   <elementGuidId>eb1334b6-b446-4cc4-a867-937e95e6b0a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employeeShift</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employeeShift']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>421825e7-04c1-4cd2-8586-a80f0fb3e4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkBox</value>
      <webElementGuid>6b43b7af-a52f-4171-a9a2-a20db638c399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employeeShift</value>
      <webElementGuid>504dbf40-e1aa-4fbd-8ef9-8dda35cdcb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employeeShift</value>
      <webElementGuid>a72bddff-4fa2-481f-ba5d-ebdd5f5cf9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>OpenEmployeeShift();</value>
      <webElementGuid>784e94c8-a855-4f61-a93a-89975dc43f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employeeShift&quot;)</value>
      <webElementGuid>6cc0d2a9-8cd3-45f1-816b-84794a260efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_48-regularize_Attendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>e1751e3d-9e7f-422c-87ce-794f296177c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employeeShift']</value>
      <webElementGuid>5769e7c2-b8f8-4ee5-a9e5-e305584c73ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAttendanceCurrentShift']/div/input</value>
      <webElementGuid>9b6208c9-33e0-4c83-8dc3-56c7967fcaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/input</value>
      <webElementGuid>fcebfb3a-bc52-4420-bf5b-18d8fa39711c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkBox' and @name = 'employeeShift' and @id = 'employeeShift']</value>
      <webElementGuid>e8e29d4f-53ab-44d8-8b21-ed12b272f7dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
