<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_---Select---Night Shift1900 TO 0600Default Shift0900 TO 1700</name>
   <tag></tag>
   <elementGuidId>1bc30e01-d47e-4842-aaf1-44825df64c4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'shifts' and (text() = '---Select---Night Shift  19:00 TO 06:00Default Shift  09:00 TO 17:00' or . = '---Select---Night Shift  19:00 TO 06:00Default Shift  09:00 TO 17:00') and @ref_element = 'Object Repository/TC_48-regularize_Attendance/Page_Home page/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#shifts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'shifts' and (text() = '---Select---Night Shift  19:00 TO 06:00Default Shift  09:00 TO 17:00' or . = '---Select---Night Shift  19:00 TO 06:00Default Shift  09:00 TO 17:00')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0decb510-1c98-4ca2-ac2e-212180f3314d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dda3b03b-9520-44fe-a9c5-83f503456961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shifts</value>
      <webElementGuid>0e7b3fed-2689-485d-bfd9-0bf0a944cca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---Night Shift  19:00 TO 06:00Default Shift  09:00 TO 17:00</value>
      <webElementGuid>24321776-45a6-488b-959e-05f6af003d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shifts&quot;)</value>
      <webElementGuid>92ecb51c-5b2b-4f41-951a-2db9e1790ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_48-regularize_Attendance/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>e1c1958d-5d2b-4fbc-a99f-117076c3ea4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='shifts']</value>
      <webElementGuid>8281e620-053e-4763-acf6-c870e0374b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='changeShiftRow']/select</value>
      <webElementGuid>2fddef04-0fb9-41e6-abcc-3d724043a678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Shift  09:00 To 17:00'])[1]/following::select[1]</value>
      <webElementGuid>ae59fe17-21d5-408b-b52e-bef31480f392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In time'])[1]/preceding::select[1]</value>
      <webElementGuid>257f309e-e1c3-4c28-91e5-37407ce6ace1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>55b08e88-c7f4-45c6-965c-8d560a72443e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'shifts' and (text() = '---Select---Night Shift  19:00 TO 06:00Default Shift  09:00 TO 17:00' or . = '---Select---Night Shift  19:00 TO 06:00Default Shift  09:00 TO 17:00')]</value>
      <webElementGuid>d0f74375-b4cf-4ab0-9ede-ed50864c6762</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
