<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View attendance dashboard</name>
   <tag></tag>
   <elementGuidId>2fd906d5-7ec6-48ad-91a1-7ba14ecadd2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;showEmpxPanelForURL('runet.do?activity=submit&amp;mod=MyAttendance&amp;cdmtHeaderBar=false', '_blank');return false;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>132d9e1a-ec37-4563-b080-ec90a02c76b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>2c979859-638d-49af-87ec-b6f52d34b325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showEmpxPanelForURL('runet.do?activity=submit&amp;mod=MyAttendance&amp;cdmtHeaderBar=false', '_blank');return false;</value>
      <webElementGuid>2b1eda64-6194-43b2-a0cd-3d0c7f4a9ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>8bee39ce-a94e-4fac-b560-9c5409adfa00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>919d1a6e-661b-4ebc-84ab-1e9410d68c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View attendance dashboard</value>
      <webElementGuid>7b337090-ea64-4950-914a-6623cad99a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dispMyAttendanceForToday&quot;)/div[@class=&quot;button-area&quot;]/a[@class=&quot;button-view&quot;]</value>
      <webElementGuid>e9878117-1dcf-41b5-943a-1d538d661656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_49-view_Attendance_Dashboard/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>67dc892a-d431-4fd7-9e67-7f555b740a31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;showEmpxPanelForURL('runet.do?activity=submit&amp;mod=MyAttendance&amp;cdmtHeaderBar=false', '_blank');return false;&quot;]</value>
      <webElementGuid>53f4e144-ba59-40e4-868d-df2b19f90be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dispMyAttendanceForToday']/div[3]/a[2]</value>
      <webElementGuid>4e59573c-5928-4c26-ab26-84ba498837bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View attendance dashboard')]</value>
      <webElementGuid>a5ee53d2-d189-4175-8769-0bece1286119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todays In-Time'])[1]/following::a[3]</value>
      <webElementGuid>b378914c-7b45-4a6a-9e8c-623696464fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly In-Time Statistics'])[1]/preceding::a[1]</value>
      <webElementGuid>e41980f8-9f94-4c47-b794-8c624df31f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View attendance dashboard']/parent::*</value>
      <webElementGuid>35cff681-d2aa-4d2f-9aaf-5a21174d8a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[8]</value>
      <webElementGuid>3b254fd2-1a9f-48b1-908c-67e94673f841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a[2]</value>
      <webElementGuid>ecbebd9a-bd4e-4121-bcfc-1403291d1d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'View attendance dashboard' or . = 'View attendance dashboard')]</value>
      <webElementGuid>0d562ac2-af66-4e6c-b62b-c0b9fcfdd107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
