<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Attendance</name>
   <tag></tag>
   <elementGuidId>0511af93-12c1-4b63-84e2-c11740f5913b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;heading_page&quot;)[count(. | //*[@id = 'heading_page' and (text() = 'Attendance' or . = 'Attendance') and @ref_element = 'Object Repository/TC_49-view_Attendance_Dashboard/Page_Home page/iframe_Self services_homePageFrame']) = count(//*[@id = 'heading_page' and (text() = 'Attendance' or . = 'Attendance') and @ref_element = 'Object Repository/TC_49-view_Attendance_Dashboard/Page_Home page/iframe_Self services_homePageFrame'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#heading_page</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id = 'heading_page' and (text() = 'Attendance' or . = 'Attendance')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>bf972c1c-8440-4d78-8e67-b4ff0c46d3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>heading_page</value>
      <webElementGuid>36d5067f-e969-4c1d-a0f1-4634e38f670e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading_page</value>
      <webElementGuid>1d320d2b-eb04-47bd-906d-eb058887994a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Attendance</value>
      <webElementGuid>bde33dd9-40de-4eb9-bc78-6e26f05023ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;heading_page&quot;)</value>
      <webElementGuid>20868c3e-63cf-419d-82c4-1e0d7da9636a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_49-view_Attendance_Dashboard/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>51bf2c0d-d3c8-45b6-9e2c-9ac02d8b8317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='heading_page']</value>
      <webElementGuid>3a25aeb5-b86b-4fca-b675-588e67b1c291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayPageContent']/div/h2</value>
      <webElementGuid>8bdc348b-67e4-4113-9a29-ce6b7199f343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::h2[1]</value>
      <webElementGuid>3da28824-48d1-405c-a0ec-957b1cfa4987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attendance']/parent::*</value>
      <webElementGuid>ddcb9b7b-5fe2-45af-8e85-b7d172285b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>e14eeb5a-4537-49dc-9a13-3365261ff11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'heading_page' and (text() = 'Attendance' or . = 'Attendance')]</value>
      <webElementGuid>888944cd-fa95-4d85-a53a-4a5f5c57d52c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
