<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>00e2102a-6c21-4346-b388-367d530e77ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='0824fce4-da6f-43f3-aa26-7ec8872bbcaf']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '0824fce4-da6f-43f3-aa26-7ec8872bbcaf' and (text() = 'OK' or . = 'OK') and @ref_element = 'Object Repository/04-TC_021-unsuccessfully_Add_Empty_Comment/Page_Home page/iframe__mycontent-right-frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#0824fce4-da6f-43f3-aa26-7ec8872bbcaf</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77e3bc97-1312-4dfe-90b6-705fcb977f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>248f5f9a-1826-4cad-9fc9-d193a6a26412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0824fce4-da6f-43f3-aa26-7ec8872bbcaf</value>
      <webElementGuid>4853ed4a-0e64-4e05-945c-de2b00c8ee87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>58565a7a-4d4b-4e22-a3ac-826477fd2484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0824fce4-da6f-43f3-aa26-7ec8872bbcaf&quot;)</value>
      <webElementGuid>d63415a9-d38d-4405-a9f5-c0afad562bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Dashboard/05 - Feed/05-TC_021-unsuccessfully_Add_Empty_Comment/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>d6414e4f-a654-448f-b44c-fa4ea1763edf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='0824fce4-da6f-43f3-aa26-7ec8872bbcaf']</value>
      <webElementGuid>d06b0f1b-63d9-4195-949a-8642a0a6dd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a1ee2f36-8277-4603-8c9f-263a43e172f6']/div/div/div[3]/div/div/button</value>
      <webElementGuid>e6101be2-70ea-4e19-ad01-cce88935df3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter the comment'])[1]/following::button[1]</value>
      <webElementGuid>9ac4ed78-03ef-4425-bfd0-274dd9b5367d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>255122a6-f35f-4ee1-b9a6-e62127a479e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>c30ba73e-58ea-4ef2-82be-632a1f0c9b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>8bee2293-e053-4418-af37-11ee476a671b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '0824fce4-da6f-43f3-aa26-7ec8872bbcaf' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>dbab74e6-be45-4b67-b7eb-52c4755fc9de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
