<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok</name>
   <tag></tag>
   <elementGuidId>277e83fc-b976-4847-973b-2e1f71b69200</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Ok' or . = 'Ok') and @ref_element = 'Object Repository/TC_53-create_A_Ticket/Page_Home page/iframe__mycontent-right-frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#960bb499-f1a8-4c32-84b3-bd952a13c341</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Request has been submitted successfully.'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c83327d-8fcb-4be8-9d8e-ccdcca9577ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>825c2187-5ba2-4e12-8201-c6e30530b1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>960bb499-f1a8-4c32-84b3-bd952a13c341</value>
      <webElementGuid>11544beb-3549-425f-adcf-c53987d67f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>8b436c4c-7ecc-4b12-8afe-1447fe2015b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;960bb499-f1a8-4c32-84b3-bd952a13c341&quot;)</value>
      <webElementGuid>aa719130-982c-4768-bfe2-4555a961764b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_53-create_A_Ticket/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>71c2df1a-a645-4a80-afc7-77ebe83fb7c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='960bb499-f1a8-4c32-84b3-bd952a13c341']</value>
      <webElementGuid>55d59b81-f203-4041-a4c0-e88ee9f98494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='76317b92-f291-48b5-8133-cdb0fa3c7b8d']/div/div/div[3]/div/div/button</value>
      <webElementGuid>a37e9d50-cf53-4c18-8a06-7d177900af5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request has been submitted successfully.'])[1]/following::button[1]</value>
      <webElementGuid>9ec3eb4c-616b-435b-81b2-23d2056211e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::button[1]</value>
      <webElementGuid>77b0a995-8cf3-4ea5-9368-faab4bdb3fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>c9cf2544-e9cc-47d0-8ca8-f7b1c51c7298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>e1dc0fb5-8949-4cbb-a2d7-a428eba282a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '960bb499-f1a8-4c32-84b3-bd952a13c341' and (text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>2524f8f4-52dc-4d16-b376-42de532949d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
