<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View or Edit Profile</name>
   <tag></tag>
   <elementGuidId>d8c577ef-fc23-4ba9-83ca-aa447058e112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary_link_myProfileOverview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='secondary_link_myProfileOverview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18d5fe7e-5f60-487b-99a0-2b1639118b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>636a9798-3bb5-44b8-9684-9cb2becd385c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary_link_myProfileOverview</value>
      <webElementGuid>be115e86-36a8-4162-97ea-c019dc7e035c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encryptURLForPanel('mod=MyProfileOverview');return false;</value>
      <webElementGuid>8b9c6f36-285c-41a1-bc1e-5abef7cb59a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>fc4eed99-798f-4197-8b49-20037c334e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View or Edit Profile</value>
      <webElementGuid>6337925e-404e-48be-ac13-c5a11cf3213e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_link_myProfileOverview&quot;)</value>
      <webElementGuid>1945d641-2c18-4b29-a8e4-447a9fa42f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_40-self-service_view_profile/Page_Home page/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>849e11af-9978-41ca-9d1e-4ddc4792466b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='secondary_link_myProfileOverview']</value>
      <webElementGuid>518c1111-9a93-44c5-9e8b-57b7f88951b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displayEmpPersonalDetail_getSecondaryLinks']/div[2]/a</value>
      <webElementGuid>5f3e81ad-1d94-4fcd-9a1a-1b59da3c929e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View or Edit Profile')]</value>
      <webElementGuid>71eb455a-8185-42ed-85cd-98767783d2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[6]/following::a[1]</value>
      <webElementGuid>9d6ae673-6584-47a5-a8fb-69f9b708eeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::a[1]</value>
      <webElementGuid>7e203bd4-1f82-4c47-9e56-911e47f08b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View or Edit Profile']/parent::*</value>
      <webElementGuid>28e520fa-2ddc-4d32-8d1e-90ca7585890e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>b6d35d48-9171-4405-a7d9-9af4d9672be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>bb9fe815-1750-4827-86cb-fe598758d7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'secondary_link_myProfileOverview' and (text() = 'View or Edit Profile' or . = 'View or Edit Profile')]</value>
      <webElementGuid>44ad970a-2a1e-472e-b713-8e1038f8e3f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
