<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Holiday Calendar</name>
   <tag></tag>
   <elementGuidId>f36ca949-205a-4df7-9c94-0b1dea644e9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_Holiday20Calendar</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'btn_Holiday20Calendar' and @href = 'javascript:void(0);' and (text() = 'Holiday Calendar' or . = 'Holiday Calendar') and @ref_element = 'Object Repository/TC_37-see_All_Attendance/Page_Home page/iframe__mycontent-right-frame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_Holiday20Calendar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07e0579d-49f1-4911-ad1b-4560925012ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_secondary</value>
      <webElementGuid>17b440ef-d321-4a98-bac1-b5c1bfb74ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Holiday20Calendar</value>
      <webElementGuid>94b390c8-b3c3-41fc-82da-2af7372c0d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>04ad6439-b61d-4591-a05a-0cde93ccb6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:encryptURLForPanel('mod=MyLeaveDetails&amp;secondaryVar=extendedDwrMode^showHolidayCalendar');return false;</value>
      <webElementGuid>8da69c84-1f26-4513-b991-b91b762a1111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Holiday Calendar</value>
      <webElementGuid>5657c2f7-d2a8-43dd-bdbd-3af1d4209553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Holiday20Calendar&quot;)</value>
      <webElementGuid>102fd94e-d661-4d94-b308-19b1f24e88f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_37-see_All_Attendance/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>a3339296-664a-47c7-81c7-52015f0eab33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_Holiday20Calendar']</value>
      <webElementGuid>ef813dc6-bb13-4ee0-9232-a76c6ff1a441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-section-panel']/div/div/div[3]/div/div/a[2]</value>
      <webElementGuid>144fa66b-0171-4e4f-9390-bc80119291b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Holiday Calendar')]</value>
      <webElementGuid>613817ec-023e-480a-b260-c1d8c4968896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply for leave'])[1]/following::a[1]</value>
      <webElementGuid>e41c1daa-bb6e-4082-999c-1fc24de399b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View in full page'])[1]/preceding::a[1]</value>
      <webElementGuid>23810e62-ca98-46f2-b1cf-e72af2615c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::a[2]</value>
      <webElementGuid>f5b92384-58a1-4bc2-95a1-d4819db039e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Holiday Calendar']/parent::*</value>
      <webElementGuid>90a350e6-4742-429f-b920-710742631b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[4]</value>
      <webElementGuid>f8b8fc6f-cbc9-4626-baa3-57135859b386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a[2]</value>
      <webElementGuid>cdd40e86-2ed2-4d3b-8b68-68f35dbbfb4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_Holiday20Calendar' and @href = 'javascript:void(0);' and (text() = 'Holiday Calendar' or . = 'Holiday Calendar')]</value>
      <webElementGuid>c0806861-b304-4246-87f0-32dd32b76037</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
