<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Resume work</name>
   <tag></tag>
   <elementGuidId>b022b48b-3be0-4664-a195-f6f5bda3d024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.attendance-widget-btn-txt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='attendance_content']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9162cdf4-308c-40e3-a441-b1079ba2140e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attendance-widget-btn-txt</value>
      <webElementGuid>aa4a8b1d-6343-4089-86a0-648fb09d511b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Resume work   </value>
      <webElementGuid>fc115c3c-05ca-4115-80d0-3efe786a771c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendance_content&quot;)/a[@class=&quot;attendance-widget-btn&quot;]/span[@class=&quot;attendance-widget-btn-txt&quot;]</value>
      <webElementGuid>1a3ad321-84ab-4978-a382-a32674ac1d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_33-start_Attendance/Page_Home page/iframe_Self services_homePageFrame (1)</value>
      <webElementGuid>6338a696-873a-4e9a-abc4-d79b6dcdefba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attendance_content']/a/span</value>
      <webElementGuid>221daead-e996-4a27-8143-6b073dcd5b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total hours'])[1]/following::span[1]</value>
      <webElementGuid>1fc94be1-ff19-4f88-85cb-616ec2d5fc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[1]/following::span[1]</value>
      <webElementGuid>abe0e531-20bd-4053-ad18-27ebe50f41cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::span[2]</value>
      <webElementGuid>edb439bf-0e9e-4282-8417-7bea436bc714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/span</value>
      <webElementGuid>6fda5633-2ca1-44ce-9bd0-9dd4b7205227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Resume work   ' or . = ' Resume work   ')]</value>
      <webElementGuid>f52adb20-3b53-484f-aa99-cea18a106739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
