<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>d31e1094-1821-473c-8ff5-bfffeff18921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='closeImageModalBox();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>08a3fbcc-2e04-47b0-8413-6fce90a640e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-img</value>
      <webElementGuid>c9240c4f-305e-4d19-9a2a-9999be7829aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closeImageModalBox();</value>
      <webElementGuid>39da0c4b-4d53-4446-b274-a06d6ec9dea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>1842f675-2cd2-408c-b30b-5d69f7742f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img-modal&quot;)/div[@class=&quot;pos-icon&quot;]/span[@class=&quot;close-img&quot;]</value>
      <webElementGuid>1a30c700-cdd0-4c8e-a3a3-d32d37dc41fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='closeImageModalBox();']</value>
      <webElementGuid>67c17804-3b2a-4a24-937a-d7c5300a8243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='img-modal']/div/span</value>
      <webElementGuid>c50c9637-0e07-482b-9308-568ed8395c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[1]/following::span[8]</value>
      <webElementGuid>939ba16d-e462-45f0-914f-0c3368c28ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::span[8]</value>
      <webElementGuid>88494b68-5694-4e76-8c54-bda190fbcaec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[8]/preceding::span[5]</value>
      <webElementGuid>e3d4ac41-4f2c-4e9f-9957-33a6eee1ba84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::span[5]</value>
      <webElementGuid>a3314093-0594-4206-8b7a-9dc0e24503d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/span</value>
      <webElementGuid>b05f249a-9da0-4fd2-bffc-23c3c5f4267f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>b98b163f-482e-4c76-9eb0-2ac1175e2930</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
