<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_e</name>
   <tag></tag>
   <elementGuidId>d1d12972-f6df-4faa-9898-e565b3ad1274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profileImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='profileImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13c04ab1-c1fd-45c9-9426-b17fda681e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profileImage</value>
      <webElementGuid>ab1b4e27-99e1-4628-9b38-44fec9d81ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profileImage</value>
      <webElementGuid>4ac0e3f3-ebce-4b8a-bae6-4428c7450d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>e</value>
      <webElementGuid>0c9949f9-1a19-4254-adbc-59223f22696c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profileImage&quot;)</value>
      <webElementGuid>937e197f-6362-4d0d-84d9-60455f11d915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='profileImage']</value>
      <webElementGuid>9d462700-6053-462a-ae02-6cddc18ad4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdownMenu1']/div</value>
      <webElementGuid>2029b359-bc9b-450c-b509-f7d3879887af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[1]/following::div[3]</value>
      <webElementGuid>2acb1521-efab-4246-b247-3b781d38b851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emp 05'])[1]/following::div[4]</value>
      <webElementGuid>0b38fc9c-0816-4f07-9635-bfce55afdc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emp 05'])[2]/preceding::div[4]</value>
      <webElementGuid>31f3cc6d-1e6f-46d5-9155-00ffa8b43132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div</value>
      <webElementGuid>291c7db8-feaa-4648-ab85-77a7cf4f3536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'profileImage' and (text() = 'e' or . = 'e')]</value>
      <webElementGuid>35b38d0a-2559-4921-b41f-fd674641f087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
