<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>5c57b5df-4d11-480c-b792-9238ab816678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='closeImageModalBox();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be9a7634-6062-49ce-adea-f74811c8f0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-img</value>
      <webElementGuid>20cef9e1-f30c-4d2c-a32a-7e8f29532990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closeImageModalBox();</value>
      <webElementGuid>11d98c83-a2a2-41a2-ab45-e59861da5bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>b8dff72a-cbc1-4ebd-ba3b-909a08ccfbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img-modal&quot;)/div[@class=&quot;pos-icon&quot;]/span[@class=&quot;close-img&quot;]</value>
      <webElementGuid>d8b33d4d-902e-484d-a1c2-d89b6e7eb3e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='closeImageModalBox();']</value>
      <webElementGuid>a51d183d-8f7f-4889-b5c8-b1e173aafdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='img-modal']/div/span</value>
      <webElementGuid>39e2ff77-7752-4c1d-87b1-2820aa97270e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[1]/following::span[8]</value>
      <webElementGuid>3653313f-99d2-4bab-a661-94523f44183f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::span[8]</value>
      <webElementGuid>9ea4525c-9fba-40e1-8f28-1f13251bfff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[8]/preceding::span[5]</value>
      <webElementGuid>c19d1c1c-80b2-4f5e-8649-1be0347d84c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/span</value>
      <webElementGuid>b804d24f-2b37-4d6b-bb89-4f81fa03472c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>c84ee2e3-0107-4eba-82e8-30fb7e3ef3e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
