<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_View details for emp  02</name>
   <tag></tag>
   <elementGuidId>50be4714-4535-4417-a0d3-d6701af31295</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG+qn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank&quot;)[count(. | //*[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG+qn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank' and (text() = 'View details for: emp  02 ' or . = 'View details for: emp  02 ')]) = count(//*[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG+qn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank' and (text() = 'View details for: emp  02 ' or . = 'View details for: emp  02 ')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS%2BS5O9pkyG05TZ1%2Bgu5nA%2Bryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs%2BVDEkshu9%2BQR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG%2Bqn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>463b60c5-516a-4c59-98a7-4ea1e690e9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG+qn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank</value>
      <webElementGuid>b4ff49e9-1ce7-458f-834c-b3546436fc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>7da6a43c-d67d-4e2d-a76a-ba6bd4929c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details for: emp  02 </value>
      <webElementGuid>d142d1ff-0a22-4a48-9bd4-4711d14d65d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG+qn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank&quot;)</value>
      <webElementGuid>2d44a9f7-9d27-4a41-8c77-283b5cde5416</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG+qn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank']</value>
      <webElementGuid>d9faf4fb-d52c-4fa1-a984-c68609571dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[2]</value>
      <webElementGuid>e795e9b0-9585-4e2f-97bb-e69d81b0b404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[8]/following::div[3]</value>
      <webElementGuid>0a8aeac9-5fd6-4af4-bc81-c3884ae47811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]</value>
      <webElementGuid>f8146c11-ee31-43a9-a113-6ec65115128e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'runet.do?activity=submit&amp;enc=wsSfF4QuJS+S5O9pkyG05TZ1+gu5nA+ryzi2i%2FBaiBfUTdwAFiKlbJmzfh4FHs+VDEkshu9+QR29KQToVK2nAP3BfEMyqMa48gdtVjWOqHeiCeJV2cu0b0XOQS2v4c9OzOYj7If1wZFu9V4P8WbPaebD5uQsYBEhDqfmi%2FKG+qn33JnqGX4w4FSucEcm60J4pPjopFWQ%2FFj6GlndnfbXZkHiFcZs7dEPnQXWMkQSlYvVH3wHK6ikOqPeTgEhG2ee$$panel$$_blank' and (text() = 'View details for: emp  02 ' or . = 'View details for: emp  02 ')]</value>
      <webElementGuid>e6bce4a5-5d97-4f89-a6ce-e379a9b02afe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
