<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_moduleName</name>
   <tag></tag>
   <elementGuidId>5eb346fb-cc17-4b06-9e68-75434bbb1118</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#moduleNameId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='moduleNameId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fac3cf3-ed26-45fc-ae70-c44d0cc4a3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>moduleName</value>
      <webElementGuid>828058b6-0eee-4bbd-8991-95cb13899e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>84px</value>
      <webElementGuid>b61c93c4-6304-4a3e-8767-54f9ed031ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-logobar form-control </value>
      <webElementGuid>a62a050e-4ee0-4026-9717-135aa447a278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>ajax_showOptions(this, 'getEmployeesByLetters', event, 'advancedFeatureSearch')</value>
      <webElementGuid>69cdc30b-2421-4c6a-848f-fbbf98a8a7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5e5be718-1f42-4584-be35-9e563fafaf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moduleNameId</value>
      <webElementGuid>6cefb6bc-8966-4d79-a5c4-29dc9f6edbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>654e622f-bd15-4c91-8475-9d76877ddd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search a feature or employee name (@name)</value>
      <webElementGuid>bd55802e-1b9f-45f2-b157-4e0519c8aeb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moduleNameId&quot;)</value>
      <webElementGuid>1b942ebf-239f-4182-a703-24d7939a33c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='moduleNameId']</value>
      <webElementGuid>5ff7cb8e-a343-40ae-9087-da32b67a13d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cd-primary-nav']/li/div/div/input</value>
      <webElementGuid>da3ab9ed-8ac6-406a-9bde-3e8cd6fbe35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/input</value>
      <webElementGuid>f75a410c-7569-4932-81d4-f3ddd7f8ab7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'moduleName' and @id = 'moduleNameId' and @type = 'text' and @placeholder = 'Search a feature or employee name (@name)']</value>
      <webElementGuid>dd48555d-7ab9-4cdd-be7c-602895822902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
