<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>793cb8d5-f5e0-43f2-a03d-846f8897f0bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='closeImageModalBox();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06f14095-a0fc-4125-a18b-9b4320516356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-img</value>
      <webElementGuid>ba2f8523-f25b-47ad-9a66-f8356592e729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closeImageModalBox();</value>
      <webElementGuid>cd360a00-dcf3-4dd7-8a7a-6682781ad9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>db6b5f82-b50b-48fa-8e0b-095b16f2321d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img-modal&quot;)/div[@class=&quot;pos-icon&quot;]/span[@class=&quot;close-img&quot;]</value>
      <webElementGuid>209d43b7-3e13-4095-abb8-314f01e82c6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='closeImageModalBox();']</value>
      <webElementGuid>aceb0285-0d67-430b-9ce9-5a792536fd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='img-modal']/div/span</value>
      <webElementGuid>d1702f3a-9d4e-47fa-beee-e566500cfb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[1]/following::span[8]</value>
      <webElementGuid>afea2cdb-7f06-4c5e-89c5-f8b86164497f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::span[8]</value>
      <webElementGuid>bfc03ed3-2c80-4b4a-a52a-87c8d5cb494a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[8]/preceding::span[5]</value>
      <webElementGuid>5462a0a6-35c2-492e-a4c1-c7b8b6ac834e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::span[5]</value>
      <webElementGuid>47512ec4-4325-4ecb-bf1b-48d928cab80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/span</value>
      <webElementGuid>283bc6b0-2b8f-4971-80cc-fa98e4250e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>e36b5f53-93b4-4092-8d87-a253e61217bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
