<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_emp 02Help</name>
   <tag></tag>
   <elementGuidId>6404ab9b-806a-455d-886d-907e96e45192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='display_page_title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#display_page_title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b5c838e3-4006-4f0d-b01c-956e8e821752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>display_page_title</value>
      <webElementGuid>6bd1f765-6441-4c07-b16f-8c0d9ef555ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>emp 02  Help</value>
      <webElementGuid>af7fd5b9-5823-4ee7-99d4-44a8043f563d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display_page_title&quot;)</value>
      <webElementGuid>4483deb3-16b2-46c5-be07-b8917246861c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='display_page_title']</value>
      <webElementGuid>d4bb980c-6bd7-44bf-9541-e2b5e5cc3966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show_hide_page_title']/div/div</value>
      <webElementGuid>5bcb26e6-ff86-446b-95b3-d028be059500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[1]/following::div[10]</value>
      <webElementGuid>557f3d1f-9d64-4a85-91ad-f4e69c66cd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::div[13]</value>
      <webElementGuid>8c785f58-2152-476d-93d8-1f09cb22612a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::div[5]</value>
      <webElementGuid>4e63a77a-fc54-47d2-be44-394c7a2f65c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div</value>
      <webElementGuid>325a307b-a98b-4803-817a-52019e488088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'display_page_title' and (text() = 'emp 02  Help' or . = 'emp 02  Help')]</value>
      <webElementGuid>a9ea00dc-5b51-4321-b57b-82b354dd341d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
