<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok</name>
   <tag></tag>
   <elementGuidId>2402a69e-825e-4c96-a859-6c323df665b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Ok' or . = 'Ok')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#0241f6e0-727e-4a09-95f3-27d18518562c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanks for submitting the feedback.'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c6fd44b-19e2-4892-bece-0510f429a274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>489b4c32-cc9a-48a6-b39c-8d6378fdd702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>0241f6e0-727e-4a09-95f3-27d18518562c</value>
      <webElementGuid>09cf642f-0b0a-475e-a3ba-4805853e7147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>952b8443-c0a4-4041-a42b-3d4b7dae4ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0241f6e0-727e-4a09-95f3-27d18518562c&quot;)</value>
      <webElementGuid>02dcc9a5-aa98-4d51-acb0-8c1237a4fe37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='0241f6e0-727e-4a09-95f3-27d18518562c']</value>
      <webElementGuid>74f2a645-c589-4d57-a252-fe6f574a84f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='546d08bb-5c54-459e-8ac3-366c7ae9a751']/div/div/div[3]/div/div/button</value>
      <webElementGuid>7b94fcde-d1c9-477e-a9b3-02c774e09d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanks for submitting the feedback.'])[1]/following::button[1]</value>
      <webElementGuid>56a09926-3154-4d1a-adfd-1a5d39352fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::button[1]</value>
      <webElementGuid>3e9ad168-08e6-4804-87d6-b620853692b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>17dda100-686e-49a8-89d5-3e111e00ef13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>16d0d5ed-59b2-45ae-a3dd-abd1bf74e2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '0241f6e0-727e-4a09-95f3-27d18518562c' and (text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>d3964d01-ecdd-4fbe-9ef0-25de29362211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
