<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_emp  04</name>
   <tag></tag>
   <elementGuidId>0ffd4249-fe0d-4c33-b4c9-1051410e635a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#1002498</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1002498']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76a208f3-74e6-4449-afa8-a4cabda30bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1002498</value>
      <webElementGuid>e73031cb-a8e2-4101-ad41-e62982cc3dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>optionDivSelected</value>
      <webElementGuid>7e60a153-c908-4cfb-9ce2-1722f71e0409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>emp  04 </value>
      <webElementGuid>d05e02cc-8e0a-4fbd-a2a5-22aec1f8a13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1002498&quot;)</value>
      <webElementGuid>e885b208-209a-403b-baaa-4d13c5d22082</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='1002498']</value>
      <webElementGuid>79806d59-7946-4ff1-bb94-68c9fcffbf81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajax_listOfOptions']/div[4]</value>
      <webElementGuid>60f9fead-3719-4a5a-9cdc-44d8761949eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[4]</value>
      <webElementGuid>6926ea9f-fd4a-433d-b363-0608b26b6e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '1002498' and (text() = 'emp  04 ' or . = 'emp  04 ')]</value>
      <webElementGuid>0f5c7da6-0fed-4d01-b5ac-8ab92412bba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
