<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rating_pulseRating_4</name>
   <tag></tag>
   <elementGuidId>ae78b2ac-e432-4829-b5f9-6062dae492dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'images/client/tenant-lite/blankStarRating.gif' and @title = '5.0' and @id = 'pulseRating_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pulseRating_4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='pulseRating_4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>77a86e4b-17d1-40bb-af0d-531f1db7bd94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/client/tenant-lite/blankStarRating.gif</value>
      <webElementGuid>77070c33-2e1b-4ae7-9d5d-9035f3c27dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>5.0</value>
      <webElementGuid>d4f0cfd0-df98-44e8-b5d3-b46b30605694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pulseRating_4</value>
      <webElementGuid>34b4e8ca-e219-4f50-9992-424c0e8e19b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changeStarRatingOptions('pulseRating','4','5','5.0');setChanged();</value>
      <webElementGuid>984653cd-ea58-4ac4-92aa-606f7834e8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pulseRating_4&quot;)</value>
      <webElementGuid>ae680a33-e987-4208-bb0c-627051ed46ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='pulseRating_4']</value>
      <webElementGuid>f49e2cef-4ba7-4f90-aa7d-ba965124c4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div[2]/div/div[3]/div/img[5]</value>
      <webElementGuid>96c0a731-63ac-49dc-ae17-fa8b1e7a51b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='5.0']</value>
      <webElementGuid>9690315c-fd4d-4398-8d05-b4a08f6f334f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[5]</value>
      <webElementGuid>96298e8d-cdeb-40fb-8e29-e127dcd2f2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/client/tenant-lite/blankStarRating.gif' and @title = '5.0' and @id = 'pulseRating_4']</value>
      <webElementGuid>d8bb758d-7643-4177-8783-41854eb2a10a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
