<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>f7f79cc7-73d8-4462-8d9c-a5d059b56686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#81319fa9-36ce-4fe9-9ef9-85d589517a1f</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'btn btn-success' and (text() = 'OK' or . = 'OK') and @ref_element = 'Object Repository/06-TC_029-click_First Half_Second Half_same_time/Page_Home page/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bdfeaddb-f181-4384-9a7d-6c31c8e15b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>26073951-7fa0-46f7-8522-b3fd28881e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>81319fa9-36ce-4fe9-9ef9-85d589517a1f</value>
      <webElementGuid>eb3ecb02-2f08-4a7d-8d49-c4c0b6612f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>4a1034e6-5583-4f01-aed5-ad56f3b1f33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;81319fa9-36ce-4fe9-9ef9-85d589517a1f&quot;)</value>
      <webElementGuid>0433b034-1ed3-402f-9da7-6c90f81d48f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/06 - Leave/06-TC_029-click_First Half_Second Half_same_time/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>c31d821f-422f-43be-9811-84aa4660c66c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='81319fa9-36ce-4fe9-9ef9-85d589517a1f']</value>
      <webElementGuid>3a17e745-1276-44f0-9b43-b3422b383872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='f18c58cb-58c2-4463-abf0-f2269646d2a8']/div/div/div[3]/div/div/button</value>
      <webElementGuid>161a2dee-325d-4477-8bda-1af1f8823a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You cannot select both partial days option on the same day of leave.'])[1]/following::button[1]</value>
      <webElementGuid>cb3c3c6f-9221-464a-ab5c-73015621e681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>13f0a7c8-9411-4c34-8efa-ba089a7c74ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>ef2a294e-27aa-416c-8f00-a7910baa3869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>f8c7e984-5c0c-4cc2-b815-d9784317b1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '81319fa9-36ce-4fe9-9ef9-85d589517a1f' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>2925b315-08d3-4509-a912-9c3ba44e08ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
