<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End on first-half of 3101_dataObject.secondHalf</name>
   <tag></tag>
   <elementGuidId>012f9c90-8d45-4582-b50d-ff4fbc3c6070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondHalf</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'dataObject.secondHalf' and @id = 'secondHalf' and @type = 'checkbox' and @ref_element = 'Object Repository/06-TC_029-click_First Half_Second Half_same_time/Page_Home page/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondHalf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33b538e3-218c-4e0e-ab4e-5d807df271fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.secondHalf</value>
      <webElementGuid>8f74b19b-dab3-4dbe-aae7-a1fd0d5f8c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eb90d0fc-7e07-4622-a16d-81735edc3036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondHalf</value>
      <webElementGuid>67360a70-ce43-4928-9d98-7082e85c7686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a42e04bf-4da7-4522-a3e6-d7c449d97d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:calculateDaysOnCheckBox('');return true;</value>
      <webElementGuid>f644befc-a6ad-4f15-bfb7-085c196f0f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondHalf&quot;)</value>
      <webElementGuid>159c906a-b1ca-4a6d-95cc-57889b8dc996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/06 - Leave/06-TC_029-click_First Half_Second Half_same_time/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>a62d4403-14f9-4cec-94ce-f4b4dc7b5d78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondHalf']</value>
      <webElementGuid>864524a5-d9a6-4a1e-a6fd-d470b5337b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveDetailSection']/div[2]/label/input</value>
      <webElementGuid>8309ba66-6a31-4541-bd8a-3b6d4c7e357a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>bc902c1f-ebb5-4b55-8851-11b2dc2648ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dataObject.secondHalf' and @id = 'secondHalf' and @type = 'checkbox']</value>
      <webElementGuid>b56ec9ed-a2f4-4889-bcd5-98f2d31176e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
