<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Invalid password. Policy Mix of numeric, lower case and upper case characters</name>
   <tag></tag>
   <elementGuidId>4218310d-5646-48c9-a08e-043572e5263a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bootstrap-dialog-message</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'Invalid password. Policy: Mix of numeric, lower case and upper case characters with minimum length of 6 characters.' or . = 'Invalid password. Policy: Mix of numeric, lower case and upper case characters with minimum length of 6 characters.') and @ref_element = 'Object Repository/Page_Home page/iframe__mycontent-right-frame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>64248f8e-4e09-4a9d-972a-737ff13b7eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bootstrap-dialog-message</value>
      <webElementGuid>1ab0239b-7675-45cb-b347-1f31d1d96c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid password. Policy: Mix of numeric, lower case and upper case characters with minimum length of 6 characters.</value>
      <webElementGuid>38d9f1b6-0d6f-4c49-86d2-38458b16db8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;650cebb8-a672-474c-9bf2-c47ffe78e642&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;bootstrap-dialog-body&quot;]/div[@class=&quot;bootstrap-dialog-message&quot;]</value>
      <webElementGuid>0922460d-fa73-41bc-a6a9-3eb04b55edad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/07 - User Profile Icon (Top Right)/Page_Home page (1)/iframe__mycontent-right-frame</value>
      <webElementGuid>0ce3486c-afa9-47cc-b5a7-45c544416b22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='650cebb8-a672-474c-9bf2-c47ffe78e642']/div/div/div[2]/div/div</value>
      <webElementGuid>c053111a-03d5-4067-8beb-ba5906fe4bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::div[3]</value>
      <webElementGuid>c1552cc7-c052-4840-b1dd-bef80ef94c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::div[4]</value>
      <webElementGuid>603af4cb-692f-48d2-bad0-3f36dee85fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ok'])[1]/preceding::div[1]</value>
      <webElementGuid>bfbc30de-1951-441e-9519-5abdf9906813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid password. Policy: Mix of numeric, lower case and upper case characters with minimum length of 6 characters.']/parent::*</value>
      <webElementGuid>e7a5c9bf-7196-430b-b0fe-8e288dede052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div</value>
      <webElementGuid>62896daa-0e38-494c-82bb-7569754d4c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Invalid password. Policy: Mix of numeric, lower case and upper case characters with minimum length of 6 characters.' or . = 'Invalid password. Policy: Mix of numeric, lower case and upper case characters with minimum length of 6 characters.')]</value>
      <webElementGuid>bcfb6020-6505-4e82-b770-1ad45b647c2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
