<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>ce9c9a27-2fc8-40da-afbe-642d2ced564a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='8c1f2392-9466-424f-b89f-9a74e9fd1fcc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#8c1f2392-9466-424f-b89f-9a74e9fd1fcc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec623397-e055-49cc-9e98-74bd5323cdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>8145101d-49ef-42a4-abc1-c03a93d05c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8c1f2392-9466-424f-b89f-9a74e9fd1fcc</value>
      <webElementGuid>25817895-0231-4298-9048-e8665e0fb9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>1532cdfb-c7d0-4c37-bd65-701bcdda13ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8c1f2392-9466-424f-b89f-9a74e9fd1fcc&quot;)</value>
      <webElementGuid>71e17647-fe74-4c9b-ba05-43ba41ecacc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Dashboard/05 - Feed/05-TC_022-view_Users_Profile/Page_Home page (1)/iframe__mycontent-right-frame</value>
      <webElementGuid>17f6ecc6-034f-46eb-b06b-fdb88ad73acf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='8c1f2392-9466-424f-b89f-9a74e9fd1fcc']</value>
      <webElementGuid>e6f1e399-97fb-470b-a9b5-8c2ae3d98c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a2fe3a95-e218-4fa2-a857-a2b68556dab6']/div/div/div[3]/div/div/button</value>
      <webElementGuid>5d0e7046-4b0f-4fe9-8b69-f48bf4d201f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>824e4b4d-22d9-4b77-a043-27fe173f1431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::button[1]</value>
      <webElementGuid>7ae86b19-5257-4cdb-8f8c-497bd85de049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '8c1f2392-9466-424f-b89f-9a74e9fd1fcc', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>f0d74fc5-2b62-42a2-8df4-5ea42998d63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>145ee7a7-aed8-4fc8-a03a-f5842dd9076f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>d07078e8-35bb-4a7c-92c8-6b2defb24411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '8c1f2392-9466-424f-b89f-9a74e9fd1fcc' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>05ff2056-67c8-4c6b-9ce4-23fec67719b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
