<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_moduleName</name>
   <tag></tag>
   <elementGuidId>f54a979b-b476-4ee1-8da9-a8554b09194b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#moduleNameId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='moduleNameId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e075e764-e0e9-493c-a78f-78738ae043b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>moduleName</value>
      <webElementGuid>f084e77c-2274-44e0-9075-d9d8a7563d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>84px</value>
      <webElementGuid>5436d9bd-2904-4fc2-9c23-affda0eb7342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-logobar form-control </value>
      <webElementGuid>c6cb25c7-9a40-42bd-892b-a05898204b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>ajax_showOptions(this, 'getEmployeesByLetters', event, 'advancedFeatureSearch')</value>
      <webElementGuid>c7b42056-9916-4783-b115-df3c644a34b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4f6f5e3d-1390-48ac-af0e-053b13e0fd52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moduleNameId</value>
      <webElementGuid>32101e96-2e2c-470f-8ba1-34b39b480ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c53d27fa-9c99-44a6-aa40-4103afda3e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search a feature or employee name (@name)</value>
      <webElementGuid>deb277ec-43c7-418e-908b-1e5afb145b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moduleNameId&quot;)</value>
      <webElementGuid>c1fd589d-db6f-4499-a9c6-0150b2053b85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='moduleNameId']</value>
      <webElementGuid>c08c82b5-71c7-4fc2-ba03-9b8cb6fff9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='cd-primary-nav']/li/div/div/input</value>
      <webElementGuid>eb6f4d3f-e1b1-4390-94ff-3f3847efde3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/input</value>
      <webElementGuid>2e8d578a-8af4-4e6b-a41c-10579e4917c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'moduleName' and @id = 'moduleNameId' and @type = 'text' and @placeholder = 'Search a feature or employee name (@name)']</value>
      <webElementGuid>b5be0bad-8787-4793-8bd6-f52ebe9444dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
