<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If checked, login details will not be_b1d379</name>
   <tag></tag>
   <elementGuidId>dbc5ed06-955a-44c7-b2c4-116b425c1007</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isPublicComputer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isPublicComputer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e5c0063-55cd-4d29-84af-043d5f96e3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>03252cf6-b79e-4899-b1e2-c3cec1d5fb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isPublicComputer</value>
      <webElementGuid>8dbe225a-9ceb-4b7b-a63f-ab2930751139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setUserDtl();</value>
      <webElementGuid>4e94df7e-64d0-40dc-8ceb-bbd529a6b40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isPublicComputer&quot;)</value>
      <webElementGuid>236f201f-cf1b-4e2b-86c0-73c25b5a51af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isPublicComputer']</value>
      <webElementGuid>23b4ea12-221b-492d-9a40-77aca3005eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9cfe3ddf-f448-4996-af8e-1e4921c1fe51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isPublicComputer']</value>
      <webElementGuid>ba57333e-d4b3-4184-9dc9-fb5ef1ee0ae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
