<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If checked, login details will not be_5dd927</name>
   <tag></tag>
   <elementGuidId>ed06d8e9-d640-4173-8aa3-73762d1baf9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usr_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usr_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0a37062-257d-4a03-b503-842dd6a1c6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de9d7f49-6492-437b-9aa8-4536ce9ef182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box userLogin</value>
      <webElementGuid>6028d968-795a-4293-bd56-7229dd5d4c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empNo</value>
      <webElementGuid>74403b34-18ec-4eda-a7ae-0f1cd0bb6dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User name</value>
      <webElementGuid>e9c5166e-0218-4dba-bf81-bce4f5585a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:detect_Key(event);</value>
      <webElementGuid>228520cd-3c61-4197-ae89-23ba3bc46aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>document.logonForm.empNo.select();</value>
      <webElementGuid>d9855448-3d2c-432c-baa0-c1e442ee6e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usr_1</value>
      <webElementGuid>b09732a2-115f-4b93-ac35-e1d36a896f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usr_1&quot;)</value>
      <webElementGuid>b7e8bfea-04d1-4632-ba28-e46f8fa4159c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usr_1']</value>
      <webElementGuid>67855cd4-b9c8-4ddb-a2f9-a28a414516b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ee42029b-9d9d-4aa3-a493-fa430e9e5d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'empNo' and @placeholder = 'User name' and @id = 'usr_1']</value>
      <webElementGuid>8ebb4552-26f3-4b08-902f-48ae37350659</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
