<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If checked, login details will not be_5c5f06</name>
   <tag></tag>
   <elementGuidId>822f729b-c301-4059-bc49-1dab5dbc3aa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9015e570-ab50-4018-a12c-ce868061b970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f9956040-e0c7-4651-aaba-239a87fa7bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>d37e5a29-1692-47e0-8201-c2232433d3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>aa825e2b-4398-4fc9-9fb1-7feb33833fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pId</value>
      <webElementGuid>12e0cd25-aa47-43df-89c1-e4271a5c0288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-box lock</value>
      <webElementGuid>3a59e250-d82e-453d-80d6-b36504d340fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:detect_Key(event);</value>
      <webElementGuid>2a427844-f0a3-48cd-99a6-b17ba61029e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>document.logonForm.password.select();</value>
      <webElementGuid>7546545b-0649-4c00-80eb-d54a157c4a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pId&quot;)</value>
      <webElementGuid>87a6d9ad-67ea-4972-b587-72b8e3091270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pId']</value>
      <webElementGuid>1939ab3c-a816-4ccd-bb94-22e93490ec43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>b66e726d-914b-4ab2-aa66-19b99f7ab5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @name = 'password' and @id = 'pId']</value>
      <webElementGuid>3d2510c5-04e7-4884-8861-2205a1f170cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
