<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leave transactions</name>
   <tag></tag>
   <elementGuidId>c85b105f-ee88-49bb-88dc-0db3ec2acad5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary_link_showMyLeaveTransaction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='secondary_link_showMyLeaveTransaction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dceaf651-ff45-421a-9652-7e6b33112a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>7e56b0d5-77d0-4c63-8f84-664c124311b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary_link_showMyLeaveTransaction</value>
      <webElementGuid>1b9d45b1-97ad-4879-bcde-703a84a9c25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encryptURLForPanel('mod=MyLeaveDetails&amp;secondaryVar=extendedDwrMode^showMyLeaveTransaction')</value>
      <webElementGuid>04f29c7e-5072-4ca7-9580-250afd380cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>0d9cc90b-db18-4cbb-b546-bf22715efd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave transactions</value>
      <webElementGuid>832823a1-8387-4fb1-be16-585bfc1ab085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_link_showMyLeaveTransaction&quot;)</value>
      <webElementGuid>c595dbf0-9c69-4f87-be27-b16aafc8fff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_45 -view_Leave_Transactions/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>657fb5d2-42c9-4b7f-93e2-c8be7f6d782d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='secondary_link_showMyLeaveTransaction']</value>
      <webElementGuid>59288136-a5bd-4cff-96af-65f2bc65e42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leaveGroup_getSecondaryLinks']/div[2]/a</value>
      <webElementGuid>aff779d5-b020-464a-abfc-80f3004d3e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Leave transactions')]</value>
      <webElementGuid>93c677c4-8424-433f-b705-4c745483cb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records are available'])[1]/following::a[1]</value>
      <webElementGuid>4922f21b-96ba-457a-9e17-756f7f8c0443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave requests'])[1]/following::a[1]</value>
      <webElementGuid>c50cc1c1-245e-4527-8d74-5d9f03287dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday Calendar'])[1]/preceding::a[1]</value>
      <webElementGuid>57f6df7b-5d89-42e3-9567-e575343ad09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Leave Policy'])[1]/preceding::a[2]</value>
      <webElementGuid>e6e5f714-20e1-4a65-ae65-203b70ea8206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leave transactions']/parent::*</value>
      <webElementGuid>811a795a-9a17-44ed-aa81-de30e9761f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[5]</value>
      <webElementGuid>2d521f66-a8ab-4e57-bf50-6cf607ac539e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[4]/div[2]/a</value>
      <webElementGuid>9701746b-ebbf-49e4-957c-fdfb960a0042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'secondary_link_showMyLeaveTransaction' and (text() = 'Leave transactions' or . = 'Leave transactions')]</value>
      <webElementGuid>2ffd2a58-4667-4cf2-8bd4-343f32860af0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
