<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Leave</name>
   <tag></tag>
   <elementGuidId>c047bcfb-ef2a-4970-a887-28849e40deef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#leaveGroup_headerV10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='leaveGroup_headerV10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>977e586a-463a-4fff-ade4-c9b867a32c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>leaveGroup_headerV10</value>
      <webElementGuid>c7cefb5f-5cfe-4c59-b674-1c52e6299f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v10widget-tite-font</value>
      <webElementGuid>e7e7c0d1-b5a9-4263-bfd2-5e15372e62b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Leave</value>
      <webElementGuid>34806f07-78a4-4681-b857-2ff79f9ea0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leaveGroup_headerV10&quot;)</value>
      <webElementGuid>786e0056-1ff2-4dd9-aaee-4767fb275bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_45 -view_Leave_Transactions/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>a8bd14b1-d731-4b71-beca-f20f51197b50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='leaveGroup_headerV10']</value>
      <webElementGuid>6daac62c-5e02-4f10-8d04-84214c8dbfa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='head-areaV10']/h2)[2]</value>
      <webElementGuid>13cdd083-b7ef-495f-a728-b6664a9bf824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View or Edit Profile'])[1]/following::h2[1]</value>
      <webElementGuid>a7469944-a657-4c84-9ad0-196f52711611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[6]/following::h2[1]</value>
      <webElementGuid>23453e57-187a-48bc-ab76-2fa48a652070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/preceding::h2[1]</value>
      <webElementGuid>3c3bfe07-4f2f-4987-8b94-7e6e0fa2e45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apr'])[1]/preceding::h2[1]</value>
      <webElementGuid>34453cb8-9150-4535-a1c1-4537068a0bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leave']/parent::*</value>
      <webElementGuid>13715151-92ee-4edd-8699-cc3263e1da5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h2</value>
      <webElementGuid>fbb1a79a-f5ec-4ab7-a1c1-7840a2cd4949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'leaveGroup_headerV10' and (text() = ' Leave' or . = ' Leave')]</value>
      <webElementGuid>06fbb0c7-dbcf-4d34-b835-c27f4955f703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
