<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok</name>
   <tag></tag>
   <elementGuidId>71f5f292-39e4-4776-bd1f-7091fe58a513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Ok' or . = 'Ok') and @ref_element = 'Object Repository/07 - User Profile Icon (Top Right)/Page_Home page/iframe__mycontent-right-frame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#40e8430a-7b6d-4668-9eb6-f329fca7b93a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Password updated successfully.'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d137ce5-e549-48c8-85b5-3f9af3b45602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>9efda4c6-40ac-4d1e-a984-90900b42d0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>40e8430a-7b6d-4668-9eb6-f329fca7b93a</value>
      <webElementGuid>99612c1d-0b28-4ab9-a37b-59b8fdb3eb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>f49ce86c-9dd2-4436-bc9f-893ec7bc3ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;40e8430a-7b6d-4668-9eb6-f329fca7b93a&quot;)</value>
      <webElementGuid>b4e5609a-6f5f-47a6-abc8-ebe402b7f85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/07 - User Profile Icon (Top Right)/Page_Home page/iframe__mycontent-right-frame</value>
      <webElementGuid>5d1ce617-8492-44e7-a6a6-f0d5e40ce1e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='40e8430a-7b6d-4668-9eb6-f329fca7b93a']</value>
      <webElementGuid>4ca231f6-71f7-47fa-81f3-e9106c76e35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ecc538af-6e7d-4f14-8bda-443a4e721a89']/div/div/div[3]/div/div/button</value>
      <webElementGuid>69bdbfb1-ff92-4811-82b1-2307d49ed759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password updated successfully.'])[1]/following::button[1]</value>
      <webElementGuid>a4f7a72a-677d-4c94-a84e-4f69ebfe7a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::button[1]</value>
      <webElementGuid>462c3068-e364-4c29-b29d-29b03fb31f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>8a2fda27-ad0b-44a7-bf22-5cf5c66890ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>d8bf5e9e-28e6-4e42-bc42-fdae0897a311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '40e8430a-7b6d-4668-9eb6-f329fca7b93a' and (text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>7fae2e24-9176-4b63-80db-53dd005593d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
