<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My tickets</name>
   <tag></tag>
   <elementGuidId>7ffe5967-8ea8-4f23-844b-6b2578d32d0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary_link_manageHelpDesk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='secondary_link_manageHelpDesk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f2910cbf-2bf7-404d-a538-9573611aff97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>5add148e-dd00-470b-a1b9-bdb38510fed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary_link_manageHelpDesk</value>
      <webElementGuid>bf3b429c-db0d-4a9a-b039-5f56551ad2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>encryptURLForPanel('runet.do?activity=submit&amp;mod=MyTicketHelpDesk')</value>
      <webElementGuid>4156c23c-12e1-4724-9886-90455e7e1473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-view</value>
      <webElementGuid>caf68f6c-133b-4b5c-8705-339b0f039272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My tickets</value>
      <webElementGuid>230625ad-f329-45be-9146-e3b8b08b3a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary_link_manageHelpDesk&quot;)</value>
      <webElementGuid>f1f93ca0-5371-4f0c-8594-14b648c0c511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_51-view_My Tickets/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>f3d19f37-3529-45dc-a53d-dc5074650894</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='secondary_link_manageHelpDesk']</value>
      <webElementGuid>9b0e12d6-1662-4fc8-a1e6-69089efdd333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showMyTicketsHelpDesk_getSecondaryLinks']/div[2]/a</value>
      <webElementGuid>9463fc5b-3bff-4e5d-8d73-0ce26e4f5eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My tickets')]</value>
      <webElementGuid>b4db16ad-d591-4b58-94fd-8f7c6e9d587c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records are available'])[2]/following::a[1]</value>
      <webElementGuid>f2c2d0da-1e92-4fb5-abe2-e3510d4bf2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[2]/following::a[1]</value>
      <webElementGuid>05539556-9ce6-468d-8adf-96af144cae2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create ticket'])[1]/preceding::a[1]</value>
      <webElementGuid>40a02ed5-92db-4213-86ea-2c978d9c024a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver: 10.10.04'])[1]/preceding::a[3]</value>
      <webElementGuid>6627bcaa-84eb-4119-8820-b71a79d5606d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My tickets']/parent::*</value>
      <webElementGuid>23e81679-8f33-4b02-a594-7e66b249db84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[9]</value>
      <webElementGuid>78314989-cecd-4cc8-9b95-be192c94b5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[4]/div[2]/a</value>
      <webElementGuid>fa993473-41da-40b8-abe9-797dd7ea862b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'secondary_link_manageHelpDesk' and (text() = 'My tickets' or . = 'My tickets')]</value>
      <webElementGuid>92e46895-7bf8-4424-a27f-e33c6294b873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
