<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My ticketsHelp</name>
   <tag></tag>
   <elementGuidId>b946c0a1-76b9-488b-a2ea-2edba35565ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;display_page_title&quot;)[count(. | //div[@id = 'display_page_title']) = count(//div[@id = 'display_page_title'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#display_page_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e1653465-b511-4402-9c5b-b72b26f99529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>display_page_title</value>
      <webElementGuid>e415b7e5-ce32-4e08-a378-4cfe061ade9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My tickets  Help</value>
      <webElementGuid>dd7aa10e-f9bf-4715-8eca-0b919f50f13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;display_page_title&quot;)</value>
      <webElementGuid>aa9476a1-3a6e-49e8-8141-68ea1cb82d27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='display_page_title']</value>
      <webElementGuid>26e7c338-43a2-490c-83ac-ea42e8fdf11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show_hide_page_title']/div/div</value>
      <webElementGuid>ecc2621e-eff1-41fc-b757-0607b59de7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self services'])[1]/following::div[10]</value>
      <webElementGuid>5e44f2c9-e42c-4b52-9016-f42610b2969a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/following::div[13]</value>
      <webElementGuid>ed4451c6-46ab-41d8-81d9-d5e2f68187d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::div[5]</value>
      <webElementGuid>b5a92348-0a42-4fa6-a3e2-de5777d3285e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div</value>
      <webElementGuid>b7917df6-3769-41f2-9ef1-d8ae5f1cdb41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'display_page_title' and (text() = 'My tickets  Help' or . = 'My tickets  Help')]</value>
      <webElementGuid>ec63b146-6138-456f-acf8-e20a53c61403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
