<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_OK</name>
   <tag></tag>
   <elementGuidId>222d2ff7-698b-4448-8ca2-7976891ccca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#223dd51a-88b3-4960-8e97-aab8018eb191</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'OK' or . = 'OK') and @ref_element = 'Object Repository/06-TC_030-applied_Earned_Leave/Page_Home page/iframe_Self services_homePageFrame']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0077966-75f3-43f2-9489-e99cc79b6c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>cd3b3f09-dc10-4143-aba8-f6a4e8cf9fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>223dd51a-88b3-4960-8e97-aab8018eb191</value>
      <webElementGuid>c8f43f39-cdef-4d9d-b6c7-f14a829b728d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>ab457b9e-e698-4a35-b41d-88400b7bceec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;223dd51a-88b3-4960-8e97-aab8018eb191&quot;)</value>
      <webElementGuid>0c886684-5503-4c07-9318-551806cbaf14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/06 - Leave/06-TC_030-applied_Earned_Leave/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>06a17e31-263e-4f6d-8615-ccec9e581f72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='223dd51a-88b3-4960-8e97-aab8018eb191']</value>
      <webElementGuid>bbd90fcd-3825-4f7d-bd9d-95f6c53d29e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='61aaf231-9d80-4b3f-bf49-e74246014015']/div/div/div[3]/div/div/button</value>
      <webElementGuid>3f3e2b53-460d-4530-98f5-b00b8ecc1d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/following::button[1]</value>
      <webElementGuid>fdc0c725-f961-422a-aa1b-51382adeca78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/following::button[1]</value>
      <webElementGuid>6ff13e32-36f1-43ef-9adb-4411e39fad78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>90d2e429-a45e-489c-b1cb-528e959c2cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>834aa7f1-23fb-43d3-a595-4b873c602452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '223dd51a-88b3-4960-8e97-aab8018eb191' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>c4a4117c-0622-4409-91f8-e9c833955c2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
