<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reason_Leave</name>
   <tag></tag>
   <elementGuidId>bf573bbe-d4c3-4468-af03-2282ee3cb13c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reasonForLeave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='reasonForLeave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4491d5c9-4a86-4cf4-9e79-0fa5a09e5833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0a036e92-cea4-4ee7-b918-f13e7cb5740a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dataObject.reasonForLeave</value>
      <webElementGuid>8a9efaa5-2236-4e72-b3aa-e8cd6d4c4ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>textLimit(this, 1000);</value>
      <webElementGuid>dc576cc0-bf9f-4527-a5ee-d92d79ef05bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reasonForLeave</value>
      <webElementGuid>1b188945-2a63-426b-823f-104ac5fe5d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reason for leave</value>
      <webElementGuid>83fe70e4-ff71-43b4-811f-89be4cb3ba4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ef6647e-b89b-4a0a-be25-45917b030180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reasonForLeave&quot;)</value>
      <webElementGuid>d99d36be-9c0f-4c92-a29f-fe92c4247450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/06 - Leave/06-TC_030-applied_Earned_Leave/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>5c219017-0594-4ec8-b7ae-f2895755251d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='reasonForLeave']</value>
      <webElementGuid>54034aa2-3b6e-4fb4-904a-e7ce2900ddae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[5]/div/div[3]/textarea</value>
      <webElementGuid>ab789b0f-f910-4955-a915-7cfeef4a6e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>67710eb4-5b99-4dc8-aeb7-e5c036f71cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'dataObject.reasonForLeave' and @id = 'reasonForLeave' and @placeholder = 'Reason for leave']</value>
      <webElementGuid>12bebda8-b7c3-46b8-b0fb-d268faadb430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
