<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok</name>
   <tag></tag>
   <elementGuidId>f3a8bcc1-cb04-4a82-8efc-a9e43bb216ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[(text() = 'Ok' or . = 'Ok')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b86e644e-ae99-49ce-9b0d-7776aada0fe4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanks for submitting your valuable suggestion.'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b4a1949-230d-45a0-86f2-8d9d1f664c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>e4c5819a-d47c-4e45-b21e-90602aeb3261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b86e644e-ae99-49ce-9b0d-7776aada0fe4</value>
      <webElementGuid>e64f25c4-6768-4e1f-8b6f-d6687dcca073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>f09dc9ba-d3f6-48ef-b7c5-b1b220528a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b86e644e-ae99-49ce-9b0d-7776aada0fe4&quot;)</value>
      <webElementGuid>c987d6af-5a84-44f2-9e02-301500115c70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b86e644e-ae99-49ce-9b0d-7776aada0fe4']</value>
      <webElementGuid>a16abccc-117b-44a0-b93b-73e5ce008ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='31ed0d82-ab0a-406c-9829-9e0b09a9669b']/div/div/div[3]/div/div/button</value>
      <webElementGuid>d19314bc-106f-49c1-a3a1-12c8286e6902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanks for submitting your valuable suggestion.'])[1]/following::button[1]</value>
      <webElementGuid>a6083ff7-cd1f-4940-acb2-28c8d57bd3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation!'])[1]/following::button[1]</value>
      <webElementGuid>6113df6e-eca7-4e4d-b79f-a2f1432d12fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>dd9eff5b-f0d5-4f35-a925-6ade5f558bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>9bc7fbd2-810e-447d-9a32-b8e82143221a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'b86e644e-ae99-49ce-9b0d-7776aada0fe4' and (text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>6c028a68-f80e-4cb7-b2a7-f10f18b10fe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
