<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_specify_Area</name>
   <tag></tag>
   <elementGuidId>919e4d07-d130-4450-93c8-10f811d9f75f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empxtrack_feedback_subject_by_client</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empxtrack_feedback_subject_by_client']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eee77c05-e555-48de-8efd-4b1dac7471dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2cd24afc-8ab0-4c16-9bfb-7ed22cf2c8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empxtrack_feedback_subject_by_client</value>
      <webElementGuid>2975f451-9f3e-417a-923f-7dcaa2ce6a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71524e27-1b62-49d3-939d-09267786ff8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Specify area</value>
      <webElementGuid>2588b4c9-6a78-43b5-876d-4a1e542c729d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empxtrack_feedback_subject_by_client&quot;)</value>
      <webElementGuid>8fc04c08-0846-4ac5-a13e-ec8c74bfa56a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empxtrack_feedback_subject_by_client']</value>
      <webElementGuid>9fc0f7d6-11ec-40fd-9eac-a28bc3d68e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>5679384a-5b8f-4f6d-aaef-9080e1e41516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>a0943a93-bba2-4088-b143-3832e60a1bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'empxtrack_feedback_subject_by_client' and @type = 'text' and @placeholder = 'Specify area']</value>
      <webElementGuid>d9893d80-3a59-4fdf-9770-dd819e410792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
