<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If checked, login details will not be_b1d379</name>
   <tag></tag>
   <elementGuidId>ac7839d0-b11f-4179-a04d-5b8a087f823e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isPublicComputer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isPublicComputer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>405a3630-73f9-4e5a-b52d-fc2d3c6ededf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0b360f80-cd73-49f6-afeb-1cc20db7014b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isPublicComputer</value>
      <webElementGuid>bdac983f-c9a8-4bbb-9604-4e862d4400aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setUserDtl();</value>
      <webElementGuid>2cb3c195-4119-471d-abf4-f8a300f394c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isPublicComputer&quot;)</value>
      <webElementGuid>0faa29ea-869a-4e60-9a96-afe312060537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isPublicComputer']</value>
      <webElementGuid>98fce7be-0c84-4d75-a9ba-95c4b0ee7218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>443e2dff-1d39-441d-8cce-a209ea3bd9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isPublicComputer']</value>
      <webElementGuid>07e3ec56-c1eb-488d-b7b1-88ed789172da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
