<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start time_startTime</name>
   <tag></tag>
   <elementGuidId>25012b39-6490-4477-98c0-942805e694f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startTime']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1680c86-bc51-4c35-8be5-e4d1395bce88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a1bdf45-e1f2-4450-8318-96e269fc752b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a76442bc-0118-4509-87bd-f56369dfe5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startTime</value>
      <webElementGuid>7e31e26c-bad0-479a-b69b-af2a2cc84cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e10edad3-3f57-48ca-970e-f8ef895f389d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javaScript:displayTimeSlot(this.id);return false;</value>
      <webElementGuid>9dad57bf-6dd9-48a9-88e8-b63e0000c344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateHhMm(this);</value>
      <webElementGuid>3bbf14d6-abc2-4992-8eec-44d8c03776ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startTime&quot;)</value>
      <webElementGuid>0ef1933b-9dcb-4ba9-816b-910a9096eb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Dashboard/04.1 - Event/TC_013-success_Add_Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>0ba1844c-efe8-4138-bbd8-52ba2ba10966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startTime']</value>
      <webElementGuid>8b268cf1-ec8b-47f1-aa96-17f22e0203dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[8]/div/input</value>
      <webElementGuid>925b7dbc-6455-4a04-8b47-8eb13ce8c79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[8]/div/input</value>
      <webElementGuid>dfa17649-0640-4b00-9eef-50cc2a9257aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'startTime']</value>
      <webElementGuid>79bb3536-ff21-4d10-b47f-d01c72218ab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
