<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_timeZone</name>
   <tag></tag>
   <elementGuidId>55e28976-5e6b-4382-84de-92ba115182b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='timeZone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#timeZone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>efd8b19a-1753-46bf-a569-0a31cc391ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timeZone</value>
      <webElementGuid>c479ee7c-25b7-46e5-af98-102c466c444f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b2725bd9-e57f-4762-b5a0-429227cc2e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi</value>
      <webElementGuid>36722938-a738-4f11-bd63-824a8ad30ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timeZone&quot;)</value>
      <webElementGuid>9083faac-cb92-4299-8cbe-f1c28e635b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Dashboard/04.1 - Event/TC_013-success_Add_Event/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>38f888fb-96b7-48c7-b594-6862dce2f289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='timeZone']</value>
      <webElementGuid>7de3c928-19b4-4248-8ad0-1860c9bb0943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[13]/div/select</value>
      <webElementGuid>30c3af92-6ef5-4c2e-af53-0c5eca596502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time zone'])[1]/following::select[1]</value>
      <webElementGuid>e7ef5182-6cd4-437e-8038-8c790d0fd0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duration'])[1]/following::select[2]</value>
      <webElementGuid>bf943c39-7365-47ca-a074-8988e1e74733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequency'])[1]/preceding::select[1]</value>
      <webElementGuid>4dcdf43c-c5b9-4201-a7d0-34b26762173b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/select</value>
      <webElementGuid>39b8bbf4-2acc-407b-8d4c-1c44c162886c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'timeZone' and (text() = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi' or . = '---Select---(GMT-08:00) Pacific Time (US &amp; Canada)(GMT-07:00) Mountain Time (US &amp; Canada)(GMT-06:00) Central Time (US &amp; Canada)(GMT-05:00) Eastern Time (US &amp; Canada)(GMT+04:00) Abu Dhabi, Muscat(GMT) Greenwhich Mean Time(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi')]</value>
      <webElementGuid>83a10f88-1c43-4d90-bfb5-2f801e18f8d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
