<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Duration_Start Date</name>
   <tag></tag>
   <elementGuidId>50c0e030-64b8-4618-96e1-28e187ce1749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startDate']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;startDate&quot;)[count(. | //*[@type = 'text' and @name = 'date_dataObject.startDate' and @id = 'startDate' and @placeholder = 'Start date' and @ref_element = 'Object Repository/06-TC_026_success_Apply_Casual Leave/Page_Home page/iframe_Self services_homePageFrame']) = count(//*[@type = 'text' and @name = 'date_dataObject.startDate' and @id = 'startDate' and @placeholder = 'Start date' and @ref_element = 'Object Repository/06-TC_026_success_Apply_Casual Leave/Page_Home page/iframe_Self services_homePageFrame'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d4681d5-1f79-4700-b660-f0385790eedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>8d870d0e-6b7b-4fbd-a377-691acb384c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c09b7b73-0c14-49e3-b549-0419fd810f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_dataObject.startDate</value>
      <webElementGuid>071c9faf-84ee-4351-96f1-f7decf841454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6a712dbd-439e-4706-b1fd-dd4704b3d32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startDate</value>
      <webElementGuid>17aea7b8-e2ba-4e89-afda-9d34c812c94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>javascript:calculateDays('Yes', '');return false;</value>
      <webElementGuid>ef2cbbd0-fb53-489f-887d-33ea25cd25ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Start date</value>
      <webElementGuid>0aec5aae-fcbf-4b38-935d-c0683ea068bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startDate&quot;)</value>
      <webElementGuid>87f71353-1cf6-4cc7-8bd2-f02b0cde56f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Dashboard/04.3 - Leave (1)/TC_026_success_Apply_Casual Leave/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>f52458c6-5d5a-4117-a193-beddab982c41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startDate']</value>
      <webElementGuid>f16e6bbd-2522-4b4e-b4f8-8f0abef7ee0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='durationCtr']/div/input</value>
      <webElementGuid>d1269a3c-9e57-4c31-bc88-425d2e99fa6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/input</value>
      <webElementGuid>c3c90eb6-a637-4fef-9ebd-d5b1c01471ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'date_dataObject.startDate' and @id = 'startDate' and @placeholder = 'Start date']</value>
      <webElementGuid>46892212-d49a-43d9-9fd5-4d2b65012c3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
