<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Due on_date_selectedEndDate</name>
   <tag></tag>
   <elementGuidId>12d4776f-0abc-493a-a0a4-082ffd397b73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedEndDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectedEndDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2a362ea-5783-45b5-af41-49f59d40da61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>288ce19d-f6a8-4aab-973b-649c150f6e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedEndDate</value>
      <webElementGuid>0358184f-eb3c-435f-9d2d-ad425efd7bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_selectedEndDate</value>
      <webElementGuid>34d0d01e-d40e-49e0-9560-c347e451492b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cal hasDatepicker</value>
      <webElementGuid>e2e661ea-d90e-431c-a96b-e47a4bb4423e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedEndDate&quot;)</value>
      <webElementGuid>7f54458e-2dc7-4566-b733-4b187a2a8a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/04 - Dashboard/04.1 - Event/TC_015-success_Add_New_Task/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>172545ee-61f5-4c9c-8771-547a51a1ceba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedEndDate']</value>
      <webElementGuid>45c7d658-ba97-47a2-9eac-47beb23ce0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventSection']/div[2]/div/div/input</value>
      <webElementGuid>bf4191ef-9adb-4db8-9f5f-21dacab9999c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>d67ec206-e5a4-4d99-8e80-e7c59144c2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'selectedEndDate' and @name = 'date_selectedEndDate']</value>
      <webElementGuid>c37701b8-90b9-4f54-b05b-369f55c7a484</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
