<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Help deskTickets</name>
   <tag></tag>
   <elementGuidId>a9cdc228-3def-4b55-9066-df0ec07cecce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showMyTicketsHelpDesk_headerV10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='showMyTicketsHelpDesk_headerV10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>2f550f81-3bea-443b-a422-ee5cbabb5905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showMyTicketsHelpDesk_headerV10</value>
      <webElementGuid>740d0177-a10d-4bd4-850c-340368f8e87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v10widget-tite-font</value>
      <webElementGuid>cf3a90f7-3554-4745-b160-bdc70c8def73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Help desk/Tickets</value>
      <webElementGuid>dc424c42-2bf2-4484-b2a2-46c46a39cb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showMyTicketsHelpDesk_headerV10&quot;)</value>
      <webElementGuid>6eb69655-2a8e-4b9b-9def-447876dd615d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/05 -Self-services/TC_55-search_ticket_ID/Page_Home page/iframe_Self services_homePageFrame</value>
      <webElementGuid>0d22f858-8979-4f62-8c77-cab7910cd00c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='showMyTicketsHelpDesk_headerV10']</value>
      <webElementGuid>a7343ea0-72be-43fa-9dbc-68e66aef9a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='head-areaV10']/h2)[4]</value>
      <webElementGuid>a02e7bf5-3e02-4d51-b620-603e26caaa8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='After 11:00'])[2]/following::h2[1]</value>
      <webElementGuid>2231465e-9504-46da-860f-da08f6af11be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Before 9:00'])[1]/following::h2[1]</value>
      <webElementGuid>63ceabb5-7344-44c1-a996-a76df55ee089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::h2[1]</value>
      <webElementGuid>4b277138-397a-4ba3-aee0-250a27fb0722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Help desk/Tickets']/parent::*</value>
      <webElementGuid>6aa82442-13f8-4320-9b73-1122d32feee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/h2</value>
      <webElementGuid>1189ed94-214c-47d7-a743-aa38f6852e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'showMyTicketsHelpDesk_headerV10' and (text() = ' Help desk/Tickets' or . = ' Help desk/Tickets')]</value>
      <webElementGuid>c91e0913-6164-4b58-9a4c-fc7c13441036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
