<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Open</name>
   <tag></tag>
   <elementGuidId>614b761c-8157-4ec3-b394-d168df17ce60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;showHidePanel_v9('allChatItems');viewPollQuestionOnBreadcrumbBar_v9();return false;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd5d6a37-faf1-4b67-a399-cb037e4994d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>e0041a75-ad25-40b4-9abb-4c02765d610e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>li_gray_default btn btn-warning</value>
      <webElementGuid>133053f4-ae4e-4746-ac36-88d6e35b5e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showHidePanel_v9('allChatItems');viewPollQuestionOnBreadcrumbBar_v9();return false;</value>
      <webElementGuid>8e635515-4d86-403c-9352-729965321afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open</value>
      <webElementGuid>9200b75e-0089-4d32-b50d-df70e64ab9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allChatItems&quot;)/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;chat-widget&quot;]/div[1]/a[@class=&quot;li_gray_default btn btn-warning&quot;]</value>
      <webElementGuid>f027e82e-f282-4650-a524-742c7dbc08a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;showHidePanel_v9('allChatItems');viewPollQuestionOnBreadcrumbBar_v9();return false;&quot;]</value>
      <webElementGuid>b49a037c-517f-41b3-a6a1-78543637e98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allChatItems']/div[2]/div/div/a</value>
      <webElementGuid>8d0f0361-7442-40c4-8aa7-354dd9e6e84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Open')]</value>
      <webElementGuid>edcc22f5-f37e-4ac6-83d9-ab6942b0e181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat'])[1]/following::a[1]</value>
      <webElementGuid>4aaf0265-d494-42ee-9dcf-11b34d6c684d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start'])[1]/preceding::a[1]</value>
      <webElementGuid>f23fa5c7-1e8b-4a71-86eb-f2f5c93fceed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open']/parent::*</value>
      <webElementGuid>067ab581-be2a-447e-8264-0a76ba407ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[4]</value>
      <webElementGuid>997db615-5023-49f5-a60c-7f031995cc61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/a</value>
      <webElementGuid>42997fea-175a-46de-8471-f8bec436a17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Open' or . = 'Open')]</value>
      <webElementGuid>ab10e7a0-dd61-41e5-891d-0fd53c8aced2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
