<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Good_DynamicRadioBox</name>
   <tag></tag>
   <elementGuidId>e36690b3-9895-44b7-bf43-4190ed97c57e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @name = 'DynamicRadioBox' and @id = 'DynamicRadioBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DynamicRadioBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DynamicRadioBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4579105d-63ab-491b-ae12-07cf367b27ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2cd21ccc-b914-43b2-881b-044912802c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DynamicRadioBox</value>
      <webElementGuid>495af446-a7cd-421a-b3a6-80db300397c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DynamicRadioBox</value>
      <webElementGuid>564270de-4000-499b-81af-07f71775334a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Good</value>
      <webElementGuid>5423962e-ead5-49a0-b088-d602697c502f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-dialog-empxtrack&quot;)/div[@class=&quot;modal fade in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;col-md-12 popup_new&quot;]/div[@class=&quot;form-group&quot;]/label[1]/input[@id=&quot;DynamicRadioBox&quot;]</value>
      <webElementGuid>24d71d42-7ae6-412c-90a7-5470dfd4f427</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DynamicRadioBox']</value>
      <webElementGuid>c01c8391-da90-4fa3-ace0-4a15b695162e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-dialog-empxtrack']/div/div/div/div[2]/div/div[2]/label/input</value>
      <webElementGuid>e41ad94e-4921-4a58-87fc-dc6bd7fa18fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>38bad0f7-d1f1-4b45-9a92-cc3e83caf7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'DynamicRadioBox' and @id = 'DynamicRadioBox']</value>
      <webElementGuid>c76623ae-70a3-4d98-9501-3ae3f2264c2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
